### ISSUE TITLE
splashtags (ja)

### ISSUE THREAD

**Issue by niyari** [frozenpandaman/s3s#1]
//First part (ja)//
荒波の
イカした
今を楽しむ
インク切れの
おいしい
帰ってきた
かけだしの
キケンな
混沌の
サバよんだ
三代目
スプラトゥーンの
秩序の
付け焼き刃の
ナイスな
逃げ足の速い
塗りたくる
ハッピーな
バンカラな
ヒーローになりたい
久しぶりの
ピチピチの
ムキムキの
無敵の
目立ちたがりな
夜ふかしの
冷静沈着な

//Second part (ja)//
3号
アイドル
赤ちゃん
アルバイター
イカ
イカノボラー
イカローラー
王者
お寿司
お祭り好き
会社員
学生
魚介類
切り込み隊長
食いしんぼう
シャケ
すりみ連合ファン
タコ
チャンピオン
天才
ナワバリバトル好き
パリピ
番長
ファッショニスタ
申し子
ルーキー
若者

**Comment by frozenpandaman** [comment]
So nice of you, thanks!

I actually already have these up here:
https://github.com/frozenpandaman/s3s/wiki/splashtags

Please let me know if you find any omissions!

What's weird is that out of all the first part & second parts of titles, 27 each in language, there doesn't seem to be a 1–1 correspondence. But for the ones that don't correspond, they do often match up translation-wise with other titles that have been revealed in trailers, etc. So the table on the wiki page has my best guesses for which will match up with each other, but the Splatfest itself should confirm – but, still, it's strange that it seems there are few language-exclusive options each, e.g. there is no way to be an "アルバイター" (Part-Timer) if playing the demo in English, and no way to be a "Maestro" or "Paradigm" (or whatever their translations might be) if playing in Japanese.

**Comment by niyari** [comment]
Only those that exist on the game.
I will explain the ones that are difficult to contextualize in Japanese later.

**Comment by niyari** [comment]
A few particularly difficult ones were selected.
word|context
-----|-----
Apprentice|見習い、始めたばかり 初心者(わかば) just started.
Attention-Seeking|お調子者 https://www.irasutoya.com/2016/12/blog-post_165.html
Blissed-Out|とても嬉しい https://www.irasutoya.com/2017/02/blog-post_70.html
Dandy|一般的には https://www.irasutoya.com/2020/02/blog-post_42.html (男女を問わない)。しかし、食べ物ではない「おいしい」なので、人物の雰囲気を重視している。
Fishy|適当、あいまい。日本では、実際の年齢より若く自称することを「サバを読む」と言います。 https://ja.wikipedia.org/wiki/%E9%AF%96%E8%AA%AD%E3%81%BF
Ink-Sloshing|(インクを)びちゃびちゃとする
Wannabe|(何か。ここではヒーロー)になりたい！という人。
Wicked-Fresh|イカちゃんは、ちょっと悪い子。
Clock Puncher|時間給で働く人。アルバイト・パートタイム。タイムカードを打刻(打つ、記録)する。 https://www.irasutoya.com/2015/08/blog-post_779.html
Raider|前衛。

**Comment by frozenpandaman** [comment]
@niyari Thanks! Last night I was actually able to get the extracted strings from the demo (前夜祭) and uploaded the matched-up translations to the [wiki page](https://github.com/frozenpandaman/s3s/wiki/splashtags) :)
