### ISSUE TITLE
I would like an option (e.g. -c) to specify config.txt.

### ISSUE THREAD

**Issue by chattytak** [frozenpandaman/s3s#103]
The config.txt must be located in the same path where s3s.py is located.
Can this be freely specified with arguments such as -c , --config option, etc.?

The s3s directory generated by git clone is expected to be deleted once when cloning or mirroring, 
so I want to keep config.txt in a separate directory.

**Comment by frozenpandaman** [comment]
Hi @chattytak,

Please see this issue for some past discussion about multiple `config.txt` files: https://github.com/frozenpandaman/splatnet2statink/issues/83#issuecomment-487323088
I don't think that's something we want to add at this time – the vast majority of people are using s3s for themselves, not other people as well, so only need one config file located in the default location. If you need this functionality, I would say to just make two copies of the folder.

>The s3s directory generated by git clone is expected to be deleted once when cloning or mirroring

Sorry, what do you mean by this? Or what's your use case? I don't think I completely understand. `config.txt` is included in `.gitignore` and is not present in the repo, so it will not be overwritten when you update the script or anything else. The file is intended to be generated separately for every user/instance of the script

**Comment by chattytak** [comment]
I wanted to run s3s.py on a Docker container to reduce dependencies in the execution environment.

Based on the official Python image, I decided to do a git clone, pip install and run s3s.py.

I made the git clone directory persistent because config.txt only works on the git clone directory.

However, the git clone command only works on an empty directory, so running the container twice doesn't work.
This means that there is no power equality.

**Comment by niyari** [comment]
> I made the git clone directory persistent because config.txt only works on the git clone directory.
However, the git clone command only works on an empty directory, so running the container twice doesn't work.

Is `git pull` available?

**Comment by lunibo** [comment]
It's not exactly what you're looking for, but I also used Docker to run S3S.
Every time the container restarts, it pulls the latest release. 

The only thing I mount is my config. 

https://git.tacam.de/Lukas/s3s-docker

**Comment by chattytak** [comment]
Hi @lunibo ,

Thank you very much.

I thought of my own method and was able to solve the problem with the following docker-compose.yml.
However, it might be smarter to use "git pull".

```
version: "3.7"

services:
  app:
    image: python:latest
    volumes:
      - ./data:/data
    command: >
      bash -c '
        cd /data
        wget https://github.com/frozenpandaman/s3s/archive/refs/heads/master.zip -O master.zip
        unzip -o master.zip
        cd s3s-master
        python -m pip install -r requirements.txt
        python s3s.py -r -M
      '

    restart: always
```

Either way, it is a shame that the initial config.txt creation process is interactive and thus does not allow for a complete container deployment.
If the process of creating config.txt could also be automated with arguments, etc., I feel that the hurdle to start using stat.ink would be lowered.
However, for non-technical users, it might be easier to use PyInstaller or something similar to run as an exe rather than Docker.

**Comment by issei-m** [comment]
Hi, I maintain an unofficial container image of s3s here and keep the latest tag is up-to-date automatically as soon as changes are made in this repository. Please consider to use it.
https://hub.docker.com/r/isseim/s3s

**Comment by frozenpandaman** [comment]
Thanks for sharing that @issei-m, and for your work there. I hope this helps users who are seeking to do something like this.

> If the process of creating config.txt could also be automated with arguments, etc., I feel that the hurdle to start using stat.ink would be lowered.

Can you help me understand how this would work, @chattytak? To me, it seems "when running the script, create `config.txt` if one doesn't exist" is the simplest approach. What would get moved to the command line, and why? I also want to prevent adding too many command line arguments by any means necessary – s3s should be very simple to run, and it's already pushing that boundary a bit.

> However, for non-technical users, it might be easier to use PyInstaller or something similar to run as an exe rather than Docker.

This is the plan, same as [what I did for splatnet2statink](https://github.com/frozenpandaman/splatnet2statink/releases).

**Comment by frozenpandaman** [comment]
Closing due to lack to reply. @chattytak feel free to respond to the above when you can/if you still want.
