### ISSUE TITLE
Feature request: option to not upload private jobs from salmon run 

### ISSUE THREAD

**Issue by lzhaxi** [frozenpandaman/s3s#104]
Usually I use private jobs to practice one specific scenario, also usually wave 1 and die on purpose wave 2. Unfortunately, splatnet does save these jobs, so I'd like an option to not upload these.

**Comment by DamianS-eng** [comment]
I had no idea Splatnet3 saves private jobs. How is this reflected on [stat.ink](https://stat.ink)? If pj's can't be filtered, may have to wait until such a filter is implemented on the site first before putting it here.

**Comment by frozenpandaman** [comment]
This is what the "ignore_private" [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) does! I'll update to the wiki to note that this includes Private Jobs too, not just Private Battles.

**Comment by lzhaxi** [comment]
Oh that's cool, didn't know that. Would it be possible to have separate ones for private jobs/private battles though? As I would still want to upload private battles and would rather not have to change config.txt every time

**Comment by frozenpandaman** [comment]
@lzhaxi Sure, I just split it into two keys as of s3s v0.3.1. Now there's `ignore_private` (only for battles – I just didn't want to rename it and break functionality for anyone who had this in their `config.txt` previously, and figured most people use it for battles) and `ignore_private_jobs`.

Please check and make sure this works for you. Thanks!

**Comment by lzhaxi** [comment]
@frozenpandaman just checked and it does work, thank you! I did discover that it shows "Previously-unuploaded jobs detected" and then ends execution if there are only private jobs unuploaded rather than saying no previously-uploaded jobs found.

**Comment by frozenpandaman** [comment]
@lzhaxi Great! I think that might be unavoidable due to the way SR Private Jobs can be detected (only in the job data itself) vs. Private Battles (you know if they're in the PB screen, and don't have to even look in the battle data).
