### ISSUE TITLE
需要一个使用教程

### ISSUE THREAD

**Issue by landor163** [frozenpandaman/s3s#105]
我仅代表部分喷射战士3的中国玩家，我们意外发现了   https://stat.ink/    这个网站，功能很好，但是在导入数据的部分，我们不明白如何操作。玩家并没有python基础，使用起来非常困难，希望可以出示一个较为简单的方法来帮助我们。

**Comment by fetus-hina** [comment]
You can write a tutorial like [this](https://vanillasalt.net/2022/10/10/how-to-use-s3s/) or [this](https://zenn.dev/hibikine/articles/1febb4eb03b604).
Note: Do not translate them without a permission. They are the work of their respective authors.

**Comment by niyari** [comment]
[See also here](https://psn.hatenablog.jp/entry/2018/05/29/235801) for instructions on how to use it in Windows.

**Comment by frozenpandaman** [comment]
Hi! Thanks for commenting! Sorry, I don't speak Chinese, so I'll use an online translator for my reply. splatnet2statink had usage instructions written in Mandarin here: https://cowlevel.net/article/1927016

> (zh) 中文版的安装说明在[这里](https://cowlevel.net/article/1927016)。

s3s is very similar and I hope it will be helpful.

你好！谢谢你的评论 对不起，我不会说中文，所以我会用在线翻译来回答。 splatnet2statink的使用说明用普通话写在这里： https://cowlevel.net/article/1927016

s3s也非常类似，我希望它能对你有所帮助。

**Comment by frozenpandaman** [comment]
Executables and bundled installations (without requiring Python) will be supported in the future.

未来将支持可执行文件和捆绑式安装（不需要Python）。

**Comment by ADeeeee** [comment]
I didn't try it, but it might work.
https://github.com/brentvollebregt/auto-py-to-exe

Having an UI would be so nice, otherwise people still need cmd on Windows for running the arguments. We could build it with AutoIT probably.

**Comment by frozenpandaman** [comment]
@ADeeeee Hmm, I wonder if it would be good to make `-r` the default mode/argument when running it as a bundled installation (like an .exe)… if possible…

**Comment by ADeeeee** [comment]
@frozenpandaman Runing the .exe in cmd or powershell is kinda okay on Windows, but still too complicated for those who are not familiar to the command line's world. If people knows how to run it in command line, the arguments seems not to be a problem for them. Just leave it the same like the .py in my opinion if it's just an executable .exe for Windows.
