### ISSUE TITLE
Splatfest Crowns Not Displayed on Stat.ink

### ISSUE THREAD

**Issue by VGmaster670** [frozenpandaman/s3s#109]
(Crosspost of https://github.com/fetus-hina/stat.ink/issues/1192 bc idk if this is a stat.ink thing or s3s thing lol)

![image](https://user-images.githubusercontent.com/72361126/218334722-881ce41a-81f8-454d-a98b-2684d9577221.png)
![image](https://user-images.githubusercontent.com/72361126/218334838-0ad6b27e-a800-4365-9140-558a64315908.png)
Stat.ink does not show Splatfest crowns for anyone despite displaying them for X-battles

**Comment by frozenpandaman** [comment]
To my knowledge, stat.ink doesn't support these yet.

https://github.com/frozenpandaman/s3s/blob/188814932ed945aeb12d4f05f0f2ba080f988612/s3s.py#L419
https://github.com/frozenpandaman/s3s/blob/188814932ed945aeb12d4f05f0f2ba080f988612/s3s.py#L558

When @fetus-hina adds support, we will too!
