### ISSUE TITLE
Future Rq: select seed files output dir

### ISSUE THREAD

**Issue by B4kedBr3ad** [frozenpandaman/s3s#110]
I would like to be able to save Seed to any directory.
For example, `python3 s3s.py --getseed ./home/seeds/`.

**Comment by frozenpandaman** [comment]
Simply run the script from a different directory, namely the directory where you want the files output, like the method mentioned in https://github.com/frozenpandaman/s3s/pull/107#issuecomment-1445027232

(NB: Your seed does not ever change.)

**Comment by B4kedBr3ad** [comment]
Okay, thanks!
