### ISSUE TITLE
Some battles may get detected as previously-unuploaded

### ISSUE THREAD

**Issue by chanchancl** [frozenpandaman/s3s#111]
[logs.txt](https://github.com/frozenpandaman/s3s/files/10846881/logs.txt)

As logs show, I run `s3s.py -r`, there will be 9 battles will be processed everytime even if they have been uploaded and this will cost some unnecessary time.

Could it be an issue?

**Comment by frozenpandaman** [comment]
@chanchancl Hmm, I'm not sure why that's happening, considering you uploaded those with s3s v0.2.0 which was after UUID generation changed (v0.1.4). For some reason, it seems the UUID of these battles isn't on stat.ink, so it's trying to reupload them – until it realizes the 'uploaded time' returned by stat.ink is much earlier than the current time, so it concludes they're duplicates and links you to the existing URL.

If it's not too much trouble, could you try deleting these specific battles off stat.ink (trash can icon) and simply reuploading them using the current version of s3s? There's been a lot of headache regarding UUIDs, in s3s development so far and SplatNet-wise, and that will be pretty easy to do. This should fix it, and I would expect that the problem should not re-occur in the future. If it _does_ keep happening after that then I'll know it's maybe an issue with private battles, or something, and something to look further look into and try to fix…

Let me know! Thanks!

**Comment by chanchancl** [comment]
Hi @frozenpandaman ,
After deleteing them from stat.ink and re-upload, there are no more reduplicate battles, I think this issue is solved, thank you for your help.
👍

**Comment by frozenpandaman** [comment]
Great! If it happens again, please re-open the issue or let me know! 🙏

**Comment by ADeeeee** [comment]
I did also deleted the duplicated battles twice and it keeps showing up and those are always private battles.

**Comment by kenny-wong** [comment]
Same as me

Wrote session_token to config.txt.
Attempting to generate new gtoken and bulletToken...
Wrote tokens for Kenny Wong to config.txt.

Validating your tokens... done.

Checking if there are previously-unuploaded battles/jobs...
Previously-unuploaded battles detected. Uploading now...
Battle already uploaded - https://stat.ink/@kennyw/spl3/e4231c12-fb17-49b4-8833-659141fa58ec
Battle already uploaded - https://stat.ink/@kennyw/spl3/93e20684-8d17-4768-9a04-cd9a927b6cf4
Battle already uploaded - https://stat.ink/@kennyw/spl3/25fd16c1-e185-421b-95a5-6859b0d0e505
Battle already uploaded - https://stat.ink/@kennyw/spl3/0829ab1f-0c52-4abf-bf96-fc6cbe02c99f
Battle already uploaded - https://stat.ink/@kennyw/spl3/ead2b400-c451-4d30-938d-9173d568a768
Battle already uploaded - https://stat.ink/@kennyw/spl3/568b1313-7ea4-4245-9ea0-1c5e35011401
Battle already uploaded - https://stat.ink/@kennyw/spl3/69d1251b-e641-45d2-8651-2f9d39f7aa14
Battle already uploaded - https://stat.ink/@kennyw/spl3/7021d509-a80e-44a2-9225-fa7caac3ee58
Battle already uploaded - https://stat.ink/@kennyw/spl3/c11bd94c-7654-4d08-bf83-2e41adce1165
Battle already uploaded - https://stat.ink/@kennyw/spl3/05d9bcf9-96c6-4b87-9f35-e662eb797050
Battle already uploaded - https://stat.ink/@kennyw/spl3/b81590e4-a0c2-426d-9680-6080080d6f0f
Battle already uploaded - https://stat.ink/@kennyw/spl3/b4cf2450-d480-46b3-9c46-51054ea1a92e
Battle already uploaded - https://stat.ink/@kennyw/spl3/e92a41a7-cb24-45ed-b81d-f75f87923719
Battle already uploaded - https://stat.ink/@kennyw/spl3/e51ceebb-01ee-4a80-b83c-79dbd5d275dc
Battle already uploaded - https://stat.ink/@kennyw/spl3/82c98ddc-c7da-49eb-b975-3a442571d92e
Battle already uploaded - https://stat.ink/@kennyw/spl3/7f326d5f-847b-4eca-b285-3e10405377bf
Battle already uploaded - https://stat.ink/@kennyw/spl3/4dcd5bbe-2d9d-4a28-9136-e15e71eca6e9
Battle already uploaded - https://stat.ink/@kennyw/spl3/ad65b142-0bed-4ba3-a0bd-81e4544f712f
Battle already uploaded - https://stat.ink/@kennyw/spl3/efe3da11-dbaf-4391-8201-b210ff7f6c0d
Battle already uploaded - https://stat.ink/@kennyw/spl3/cfd17ba2-f135-4291-83d7-156419d010e8
Battle already uploaded - https://stat.ink/@kennyw/spl3/10315a73-3a09-4f92-9bd7-5285b7f53bc8
Battle already uploaded - https://stat.ink/@kennyw/spl3/4fcfac16-69ef-4b73-8360-fcea0ece3ab8
Battle already uploaded - https://stat.ink/@kennyw/spl3/628cf948-fa49-44de-a280-9cf2ccbee845
Battle already uploaded - https://stat.ink/@kennyw/spl3/6089c298-9843-47e3-b792-dd69768da9db
Battle already uploaded - https://stat.ink/@kennyw/spl3/dabd1ea2-ca1e-4fc5-a137-5f5f847390dd
Battle already uploaded - https://stat.ink/@kennyw/spl3/364c5aed-0c06-47ee-9c50-322576fcbd8f
Battle already uploaded - https://stat.ink/@kennyw/spl3/5f04c05e-a3be-4b6e-9a3e-3aed5c061b24
Battle already uploaded - https://stat.ink/@kennyw/spl3/a4ac828c-bdac-4aeb-9a7d-44157636d39b
Battle already uploaded - https://stat.ink/@kennyw/spl3/a851edcc-2bf0-449c-a4e7-ee4dac42b8b7
Battle already uploaded - https://stat.ink/@kennyw/spl3/5cf043cd-bff9-4626-9444-653192046603
Battle already uploaded - https://stat.ink/@kennyw/spl3/39fef708-ee64-41b1-8809-afc467e27ba1
Battle already uploaded - https://stat.ink/@kennyw/spl3/cd1c3789-7d6a-4506-9fbf-cfa50bd05d73
Battle uploaded to https://stat.ink/@kennyw/spl3/829861b5-8c47-45c4-8c5a-7b146b964537
Battle uploaded to https://stat.ink/@kennyw/spl3/1b48bc7d-890d-49f0-a9b5-8ad980dc8e8b
Battle uploaded to https://stat.ink/@kennyw/spl3/0c1f94ea-c52e-47a4-9d72-51ddd6afbb8a
Battle uploaded to https://stat.ink/@kennyw/spl3/16e62353-bc4e-421e-b4aa-cc4b80d120f3
Battle uploaded to https://stat.ink/@kennyw/spl3/7b86605a-8227-4787-845a-5a4660fe52d4
Battle uploaded to https://stat.ink/@kennyw/spl3/e9ea105a-124f-44ac-9041-116c1b4b5247

**Comment by frozenpandaman** [comment]
> Same as me

@kenny-wong Interesting… notably, yours are not Private Battles, hmm…

**Comment by beanjamin25** [comment]
I think that this is the same as issue #102 where I think the problem is that we get the last 200 battles of 50 each of private, turf, anarchy, and x battle, but we dont get the last 50 of each queue from stat.ink, we just get the last 200 battles...

**Comment by beanjamin25** [comment]
Looking more at stat.ink, I saw that they were now providing the last 500 uuids, but also that you can filter by lobby using the query param `lobby` (values of `regular`, `bankara`, `private`, `xmatch`, `splatfest_open`, `splatfest_chellenge`). If you use that filter then you can get back the last 500 of each type of lobby if you make several requests instead of just one. An example in #116 
This _should_ make sure that any battle we get from splatnet should either be new or already uploaded and in the list we get from stat.ink

**Comment by ry42** [comment]
same for me - list below

Checking if there are previously-unuploaded battles/jobs...
Previously-unuploaded battles detected. Uploading now...
Battle already uploaded - https://stat.ink/@ryr4242/spl3/384dae03-79e4-455c-8eaf-e19e7b96e459
Battle already uploaded - https://stat.ink/@ryr4242/spl3/9f1f9ee5-b623-4c62-b823-69f58bd47a7d
Battle already uploaded - https://stat.ink/@ryr4242/spl3/4ab51d8e-d34e-47f0-922e-11327e6357b9
Battle already uploaded - https://stat.ink/@ryr4242/spl3/689c7485-ee6a-4f8c-911c-59ca511ad2cd
Battle already uploaded - https://stat.ink/@ryr4242/spl3/2ed94260-259e-4620-a20d-fc42aa5f94c3
Battle already uploaded - https://stat.ink/@ryr4242/spl3/5c8c9915-fa8c-4dbf-ac20-4f38cc88c602
Battle already uploaded - https://stat.ink/@ryr4242/spl3/0055fcda-c2f4-4047-9623-3ba1c1f89325
Battle already uploaded - https://stat.ink/@ryr4242/spl3/4f944aaf-fb42-4aae-834a-1278553b279e
Battle already uploaded - https://stat.ink/@ryr4242/spl3/82c908a1-77c0-4b08-9c27-4944b5e6c645
Battle already uploaded - https://stat.ink/@ryr4242/spl3/d4da80fd-9ecf-4cfc-86b6-472b906dbb78
Battle already uploaded - https://stat.ink/@ryr4242/spl3/048e51ed-fd46-4d17-9fbe-0fd283c9ff8c
Battle already uploaded - https://stat.ink/@ryr4242/spl3/80183e74-7910-4c7d-8d42-534d3a5caefe
Battle already uploaded - https://stat.ink/@ryr4242/spl3/4c0448a0-771a-497c-a555-66cdfbbd7cf5
Battle already uploaded - https://stat.ink/@ryr4242/spl3/3d949f38-fdbd-4854-9e4b-e5f17d35c04e
Battle already uploaded - https://stat.ink/@ryr4242/spl3/733a2760-25ee-4685-8705-89df12049797
Battle already uploaded - https://stat.ink/@ryr4242/spl3/3d82636f-7ed4-4bd0-8d31-86ccc4073332
Battle already uploaded - https://stat.ink/@ryr4242/spl3/d4c8e42d-b37f-4a77-b0c4-1e365e8a7078
Battle already uploaded - https://stat.ink/@ryr4242/spl3/b32d49d2-520f-40f8-80ca-88fed493fe33
Battle already uploaded - https://stat.ink/@ryr4242/spl3/2f42c0ce-9e23-4356-bdfd-965f793ffb21
Battle already uploaded - https://stat.ink/@ryr4242/spl3/860bccd4-fb19-48f2-8b34-1230fbb1719c
Battle already uploaded - https://stat.ink/@ryr4242/spl3/ac675849-05dd-4b78-adf3-bdd72c713cd5
Battle already uploaded - https://stat.ink/@ryr4242/spl3/6ca13c26-0790-4011-bb62-d793fde7f791
Battle already uploaded - https://stat.ink/@ryr4242/spl3/26b9550d-378f-4497-9438-2bee3076ba5c
Battle already uploaded - https://stat.ink/@ryr4242/spl3/96adc371-8268-47d6-8374-f1b3198567ce
Battle already uploaded - https://stat.ink/@ryr4242/spl3/5949aaab-d4d2-4aab-8cae-a95b98893e02
Battle already uploaded - https://stat.ink/@ryr4242/spl3/cf5a56c6-d1f2-45f5-bbe8-5bde7872c710
Battle already uploaded - https://stat.ink/@ryr4242/spl3/07bdd501-3724-4f9a-93b3-e58c11ac154d
Battle already uploaded - https://stat.ink/@ryr4242/spl3/9d3d716b-1a5e-4fe4-a2df-995e2fd0460b
Battle already uploaded - https://stat.ink/@ryr4242/spl3/481e0e6e-a196-4391-b538-28308ea99fa0
Battle already uploaded - https://stat.ink/@ryr4242/spl3/91463ae8-4737-40e6-958a-5dafaf6cff95
Battle already uploaded - https://stat.ink/@ryr4242/spl3/80671545-ba92-468f-8fd8-bcebd5ff774e
Battle already uploaded - https://stat.ink/@ryr4242/spl3/ab7e5dd3-3020-4950-bf41-2f0f40e00d86
Battle already uploaded - https://stat.ink/@ryr4242/spl3/49374ae0-ebf7-411b-a926-e3a3c84c5568
Battle already uploaded - https://stat.ink/@ryr4242/spl3/8c2f5a45-5abe-4bb9-a60c-e6d13141b887
No previously-unuploaded jobs found.
