### ISSUE TITLE
Error caused by the new slopsuits in Salmon Run

### ISSUE THREAD

**Issue by zhu2qian1** [frozenpandaman/s3s#112]
サーモンランに新しく追加されたツナギが原因でエラーが起きています

```
Traceback (most recent call last):
  File "/home/zhu2qian1/gitrepo/spl/./s3s.py", line 2006, in <module>
    main()
  File "/home/zhu2qian1/gitrepo/spl/./s3s.py", line 1974, in main
    check_if_missing(which, blackout, test_run, skipprefetch) # monitoring mode hasn't begun yet
  File "/home/zhu2qian1/gitrepo/spl/./s3s.py", line 1438, in check_if_missing
    fetch_and_upload_single_result(id, noun, isblackout, istestrun)
  File "/home/zhu2qian1/gitrepo/spl/./s3s.py", line 1355, in fetch_and_upload_single_result
    post_result(result, False, isblackout, istestrun) # not monitoring mode
  File "/home/zhu2qian1/gitrepo/spl/./s3s.py", line 1167, in post_result
    payload = prepare_job_result(results[i]["data"], ismonitoring, isblackout, overview_data, prevresult=prevresult)
  File "/home/zhu2qian1/gitrepo/spl/./s3s.py", line 1051, in prepare_job_result
    player_info["uniform"] = translate_slop[slop_num]
KeyError: 8
```

**Comment by frozenpandaman** [comment]
Thanks! @Minaraii just messaged me about this too. I think they're planning on sending me their JSONs so I can get these added tonight.

**Comment by zhu2qian1** [comment]
Thank you!

**Comment by frozenpandaman** [comment]
I've obtained the [SplatNet 3 keys](https://github.com/frozenpandaman/s3s/wiki/%7C-stat.ink-&-splatnet-keys#uniforms) for the gear. Now we just need to wait for stat.ink to add support.

**Comment by zhu2qian1** [comment]
Thanks. I hope stat.ink adds support soon.

**Comment by frozenpandaman** [comment]
As of d61b0ed (v0.3.3), this will no longer throw an error, and the jobs will still upload to stat.ink, but it will print a warning. Since the data is incomplete (unknown gear) it would be good to delete these jobs & re-upload them later once @fetus-hina adds support.

**Comment by fetus-hina** [comment]
Sorry for waiting.
stat.ink is now ready for new gloopsuits.

@frozenpandaman The new keys like `orange_gloopsuit` and now accepts ID-number-aliases.
more information: https://stat.ink/api-info/salmon-uniform3

**Comment by frozenpandaman** [comment]
Thanks Hina!! Awesome! I made it so it sends the ID aliases instead of strings now.
