### ISSUE TITLE
9403 Invalid token.

### ISSUE THREAD

**Issue by uptownboy** [frozenpandaman/s3s#113]
thanks for providing this excellent tools.
I found the upload script didn't work maybe due to the new season update? It was fine last night.

error msg as below:
Wrote session_token to config.txt.
Attempting to generate new gtoken and bulletToken...
Error from Nintendo (in Account/Login step):
{
  "status": 9403,
  "errorMessage": "Invalid token.",
  "correlationId": "a3dceb99-96b92fcc"
}
Re-running the script usually fixes this.

**Comment by tetrahedrl** [comment]
Yeah, just started experiencing that too. Imink API still up, hope Nintendo haven’t changed things again…

**Comment by niyari** [comment]
I have been putting it off, but it is a single point of failure and I hope to resolve it eventually.

**Comment by frozenpandaman** [comment]
I've just updated the script to allow you to more easily use the old version of the app to generate cookies. In `iksm.py`, just change the `USE_OLD_NSOAPP_VER = False` statement at the top to say `= True`.

I don't want to make it do this automatically as it would involve sending invalid requests to Nintendo servers every time the script is run and then waiting to receive an error – plus, at some point Nintendo does start invalidating tokens generated with previous versions of the app (and on your actual phone, it forces you to update, and s3s doing anything the actual app does not do has the potential for complications). The upside to, right now, having s3s fetch the current app version automatically is you won't run into errors most of the time when the app updates – but the one downside is you instead _will_ instead get errors in cases like today's, if and when the update changes `f` generation (infrequently).

Please update s3s to v0.3.3 and then change this line at the top of `iksm.py` to get automatic cookie generation working again. If people think it would be better, I could move this to a [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) in `config.txt`?

When the imink API updates, I'll update the `NSOAPP_VER_FALLBACK` variable to `2.5.0` – please keep an eye on this issue and it would probably be best to revert your `iksm.py` at that time.

**Comment by frozenpandaman** [comment]
I've just updated the script to allow you to more easily use the old version of the app to generate cookies. In `iksm.py`, just change the `USE_OLD_NSOAPP_VER = False` statement at the top to say `= True`.

I don't want to make it do this automatically as it would involve sending invalid requests to Nintendo servers every time the script is run and then waiting to receive an error – plus, at some point Nintendo does start invalidating tokens generated with previous versions of the app (and on your actual phone, it forces you to update, and s3s doing anything the actual app does not do has the potential for complications). The upside to, right now, having s3s fetch the current app version automatically is you won't run into errors most of the time when the app updates – but the one downside is you instead _will_ instead get errors in cases like today's, if and when the update changes `f` generation (infrequently).

Please update s3s to v0.3.3 and then change this line at the top of `iksm.py` to get automatic cookie generation working again. If people think it would be better, I could move this to a [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) in `config.txt`?

When the imink API updates, I'll update the `NSOAPP_VER_FALLBACK` variable to `2.5.0` – please keep an eye on this issue and it would probably be best to revert `USE_OLD_NSOAPP_VER` back to `False` at that time.

**Comment by frozenpandaman** [comment]
The imink API has been fixed (that didn't take long! well, now we have that change for the future!)

So please revert `iksm.py` back to say `USE_OLD_NSOAPP_VER = False` and update. :)
