### ISSUE TITLE
python keeps automatically closing the program

### ISSUE THREAD

**Issue by EATMYTOES1** [frozenpandaman/s3s#117]
the program automatically closes for me without any imput the second it opens, im not sure what is wrong or how to fix this

**Comment by EATMYTOES1** [comment]
i apologize if its a very simple fix, im new to python and just cant seem to figure out the issue

**Comment by frozenpandaman** [comment]
Please share what command you're running.

**Comment by EATMYTOES1** [comment]
im not running any command, im simply opening the program

**Comment by frozenpandaman** [comment]
There's not a pre-compiled executable that can be run yet. Did you read the readme of how to use the program? You need to open the command line and run `python s3s.py`.
