### ISSUE TITLE
can I use this to get the battle history from when I start to play this game to now?

### ISSUE THREAD

**Issue by q3001099** [frozenpandaman/s3s#120]
I start to use this to get the battle history today,but  I started to play splatoon3 last year. Can I use this to get the battle history from when I start to play?

**Comment by frozenpandaman** [comment]
Sorry, no, only the previous 50 battles of each mode are available on SplatNet. After that the data is deleted from Nintendo's servers – so unless you were using s3s previously to back it up to stat.ink that data is now lost.

**Comment by q3001099** [comment]
ok,thank you!
