### ISSUE TITLE
Salmon run jobs cannot be uploaded if eggstra work jobs have been completed

### ISSUE THREAD

**Issue by RyouSkye** [frozenpandaman/s3s#121]
Hello, I've never put in an issue to a public repo so I hope this is enough info.

As of this weekend, a new salmon run mode "Eggstra Work" was introduced. However if you try to upload your salmon run results with the current version of s3s, an error occurs:

```
s3s v0.3.4
Checking if there are previously-unuploaded jobs...
Validating your tokens... done.

Previously-unuploaded jobs detected. Uploading now...                                                                                                                                                                                      
Traceback (most recent call last):
  File "/home/rysk/Downloads/s3s/s3s.py", line 2000, in <module>
    main()
  File "/home/rysk/Downloads/s3s/s3s.py", line 1968, in main
    check_if_missing(which, blackout, test_run, skipprefetch) # monitoring mode hasn't begun yet
  File "/home/rysk/Downloads/s3s/s3s.py", line 1432, in check_if_missing
    fetch_and_upload_single_result(id, noun, isblackout, istestrun)
  File "/home/rysk/Downloads/s3s/s3s.py", line 1349, in fetch_and_upload_single_result
    post_result(result, False, isblackout, istestrun) # not monitoring mode
  File "/home/rysk/Downloads/s3s/s3s.py", line 1161, in post_result
    payload = prepare_job_result(results[i]["data"], ismonitoring, isblackout, overview_data, prevresult=prevresult)
  File "/home/rysk/Downloads/s3s/s3s.py", line 905, in prepare_job_result
    payload["title_after"]     = utils.b64d(job["afterGrade"]["id"])
TypeError: 'NoneType' object is not subscriptable
```

I locally got around this by skipping jobs that have `results[i]["data"]["coopHistoryDetail"]["rule"]` as "TEAM_CONTEST" and not having them run through prepare_job_result and only upload my regular result, which was successful

There's very likely a better way but I'm not very familiar with s3s and python in general.

**Comment by frozenpandaman** [comment]
Sorry about that! I haven't gotten to play Eggstra Work yet. I'll get this fixed at some point in the next day.

For now, if you foresee playing more than 50 jobs, remember to export your results with `-o` so they can be imported with `-i` later.

**Comment by RyouSkye** [comment]
No worries! I don't play that much SR so I won't get that many, I just wanted to give you a headsup :) Thank you for your work on s3s!

**Comment by frozenpandaman** [comment]
Eggstra Work is now supported as of v0.4.0 / d46ece0!
