### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by TheMythicalMatty** [frozenpandaman/s3s#124]
So what do you do when the command line for downloading Stat.ink gives you an invalid syntax error?

**Comment by frozenpandaman** [comment]
What command are you running?

**Comment by TheMythicalMatty** [comment]
git clone https://github.com/frozenpandaman/s3s.git

**Comment by frozenpandaman** [comment]
Is Git installed?

**Comment by TheMythicalMatty** [comment]
Yes

**Comment by frozenpandaman** [comment]
What happens when you run `git --version`?

**Comment by TheMythicalMatty** [comment]
I get a NameError. git is not defined

**Comment by frozenpandaman** [comment]
You should be running these commands from Command Prompt/PowerShell/Terminal, not from within Python. Follow the steps in the readme! :)
