### ISSUE TITLE
Automatic token generation is broken (9403: Invalid token.)

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#125]
Nintendo put out a tweet regarding third-party tools (although s3s is not technically a smartphone app, ha!)

https://twitter.com/nintendo_cs/status/1661198043461603328

> **[Notice] We have confirmed the existence of smartphone apps that spoof legitimate apps for Splatoon 3 and other network services, and which fraudulently access our company's servers. Use of these types of apps may compromise your security and personal information, and there is a possibility of unexpected damage. Please be careful.**

In conjunction, as of last night, the NSO app has also been updated to v2.5.1, and as of today servers have stopped accepting tokens generated by earlier versions. Despite updates to the imink API (and similar tools like nxapi-znca-api and nsotokengen) in attempt to rectify this, as is usually done when the NSO app updates, 9403 errors are still being returned, i.e. **automatic token generation is currently broken**.

Please follow the [mitmproxy instructions](https://github.com/frozenpandaman/s3s/wiki/mitmproxy-instructions) to continue using s3s for the time being.

**Comment by niyari** [comment]
In the case of an error caused by an external factor, it seems necessary to display an easy-to-understand error message.
Specifically, display an explanation such as "Please wait a moment".

**Comment by frozenpandaman** [comment]
https://github.com/samuelthomas2774/nxapi/discussions/10#discussioncomment-5995498

Changes have been summarized (publicly) here. s3s will be updated shortly when support for the new necessary parameters are added to the imink API.

**Comment by niyari** [comment]
s3s is now available again.

**Comment by frozenpandaman** [comment]
This should be resolved now!

**Comment by SicariusREAL** [comment]
still getting this error

**Comment by niyari** [comment]
When creating authentication information, an error may occur if there is a load due to access concentration etc.
Are you still getting the error?

**Comment by SicariusREAL** [comment]
yes

**Comment by frozenpandaman** [comment]
@SicariusREAL Please try deleting your `config.txt` and running the script again.

**Comment by frozenpandaman** [comment]
@SicariusREAL As multiple people have pointed out to you before, this is not an s3s error.

https://github.com/spacemeowx2/s3si.ts/issues/69
