### ISSUE TITLE
Challenges not getting caught in -r

### ISSUE THREAD

**Issue by Peri0dic** [frozenpandaman/s3s#129]
Not sure if I'm the only one but it seems as if the challenge games I played are not getting uploaded when I run -r, It still catches open games played after.

**Comment by frozenpandaman** [comment]
Hm, it should. `-r`'s `check_if_missing()` calls `fetch_json()` in a way that queries Challenges & gets those battle IDs:
https://github.com/frozenpandaman/s3s/blob/ecc8c26c27226a9671f36a7d66086cde0f333491/s3s.py#L226-L227
https://github.com/frozenpandaman/s3s/blob/ecc8c26c27226a9671f36a7d66086cde0f333491/s3s.py#L286-L291

Can you verify you're using s3s v0.5.1?

**Comment by Peri0dic** [comment]
Oops my bad they actually did get caught, I think I just ran the -r the first time on an old version so it uploaded a Unknown battle type onto stat.ink. My bad 👍

**Comment by frozenpandaman** [comment]
Ah, no worries! Glad you figured out what happened.

You should be able to delete them from stat.ink and reupload with `-r` (unless you've played more than 50 Challenge battles already!)
