### ISSUE TITLE
Auto update on Debian

### ISSUE THREAD

**Issue by Scromx** [frozenpandaman/s3s#130]
Hello,

I would like to contact you, because I would like to know if it is possible to update automatically?

I would like to install S3S on a Debian server that will run the program H24.

However, I would like to know if it would be possible for it to update automatically and restart the automatic search?

Thank you for your answer

**Comment by frozenpandaman** [comment]
Hi! See https://github.com/frozenpandaman/s3s/issues/123 for a number of different solutions

**Comment by Scromx** [comment]
Thank you,

Another question at the same time,

is it possible to put several profiles in the match search?

For example :

Profile Stat ink 1 and Token nintendo 1
Stat Ink 2 profile and Token Nintendo 2
...
