### ISSUE TITLE
Multi-profile

### ISSUE THREAD

**Issue by Scromx** [frozenpandaman/s3s#131]
Hello, sorry to open another post,

My question is, for example, is it possible to configure several profiles?

For example :

Token Stat.ink 1
Token Nintendo 1

Token Stat.ink 2
Token Nintendo 2

... ETC

and send stats for all configured profiles?

**Comment by frozenpandaman** [comment]
For this usage, please just have make different copies of the folder & script. It's lightweight (< 400kb) so perfect for this type of thing!

Previous discussion at https://github.com/frozenpandaman/s3s/issues/103#issuecomment-1401457636

**Comment by Scromx** [comment]
Would it be possible for me to launch the orders at the same time?

Example: python s3s1/s3s.py s3s2/s3s.py -r -M

**Comment by frozenpandaman** [comment]
Just use two different Terminal windows.

```zsh
$ python path/to/s3s1/s3s.py -r -M
```
```zsh
$ python path/to/s3s2/s3s.py -r -M
```

**Comment by Scromx** [comment]
So the worry is that I won't be on Windows, but on a Debian VMS thanks to my freebox.

And I must admit that I'm not necessarily comfortable with Debian and that I'd like my freebox to send my team's stats all the time.

Hence the idea of trying to send several profiles at the same time.

**Comment by frozenpandaman** [comment]
I'm not familiar with Debian or what a freebox [(?)](https://en.wikipedia.org/wiki/Freebox) is, sorry! I would think you can just have multiple folders set up:
```
└── s3s-for-team
    ├── person1
    │   ├── config.txt
    │   └── s3s.py
    ├── person2
    │   ├── config.txt
    │   └── s3s.py
    └── person3
        ├── config.txt
        └── s3s.py
```

And then set cron jobs to regularly run `python path/to/s3s-for-team/person1/s3s.py -r`, `python path/to/s3s-for-team/person2/s3s.py -r`, `python path/to/s3s-for-team/person3/s3s.py -r`, etc.
