### ISSUE TITLE
I made a setup/helper script and an AUR package

### ISSUE THREAD

**Issue by North-West-Wind** [frozenpandaman/s3s#132]
I'm just here to inform you that I made something. In case you receive any issues reported by users regarding the AUR package, please redirect them to me.

Here's the repository: https://github.com/North-West-Wind/s3s-setup

Love your work!

**Comment by frozenpandaman** [comment]
This is cool, thanks @North-West-Wind, and appreciate the heads up as well! I don't know much about Arch – what's your use case here, or how does it work? Should I link this on the [automation](https://github.com/frozenpandaman/s3s/wiki/automation) wiki page?

Also fun fact: s3s doesn't stand for splatnet3statink, it's just… its own thing, now ;) Sort of like how the band Andrew Jackson Jihad officially renamed themselves to AJJ lol

**Comment by North-West-Wind** [comment]
> what's your use case here, or how does it work?

First time running the script will install s3s to `~/.config/s3s`, since I read from #131 you suggested multi-profile to just be multiple copies of s3s.

After the initial run, the script redirects all passed arguments to s3s.py, so one can run it like this:
```
$ s3s [-M [N]] [-r] [-nsr | -osr] [--blackout]
```
This script wraps the original command so that running the command will always read config from `~/.config/s3s` regardless of the working directory.  
It also adds an extra function to copy gtoken directly to the clipboard, in order to be used for browsing SplatNet 3.

The repo also contains a systemd service to automatically update and upload battles/jobs every 5 minutes.

> Should I link this on the [automation](https://github.com/frozenpandaman/s3s/wiki/automation) wiki page?

 That would be great! My repo's readme already has the installation instructions.

> s3s doesn't stand for splatnet3statink

Oh lol, didn't know that. Will correct it asap

**Comment by frozenpandaman** [comment]
Very cool, thanks!!
