### ISSUE TITLE
Python script crash

### ISSUE THREAD

**Issue by Mecha993** [frozenpandaman/s3s#133]
Whenever I enter my api token and press accept for the language, the script crashes and anytime I try to open it back up it closes immediatly. Any tips?

**Comment by frozenpandaman** [comment]
What command are you running?

**Comment by Mecha993** [comment]
do you mean the python script? if so its the s3s one

**Comment by frozenpandaman** [comment]
What command are you typing into Command Prompt to run s3s?

**Comment by Mecha993** [comment]
oh im not using command prompt to run it. I setup the files and everything so im just clicking the actual python file in the folder

**Comment by frozenpandaman** [comment]
Precompiled executables are not yet available for s3s, so clicking on it won't work.

Please follow the setup instructions in the readme, paying attention to step 5 which points you to the "usage" section.

**Comment by Mecha993** [comment]
so everything will be done using command prompt right?

**Comment by frozenpandaman** [comment]
Yep, s3s is a command line tool :)

**Comment by Mecha993** [comment]
when i type "python s3s.py" it asks if i want to upload salmon or battle replays but after that it just says exititing so I cant answer the question

**Comment by frozenpandaman** [comment]
Please read the readme.

https://github.com/frozenpandaman/s3s#tips-for-using-s3s

**Comment by Mecha993** [comment]
alright i figured everything out thanks for the help!

**Comment by frozenpandaman** [comment]
Glad you solved it, yay! 💪
