### ISSUE TITLE
Upload exported results

### ISSUE THREAD

**Issue by zhxie** [frozenpandaman/s3s#134]
I want to upload exported results to stat.ink using s3s v0.5.2.

When export results locally through `s3s -o`, s3s will save the results of battles and coops to `exports/results/{playedTime}.json` and `exports/coop_results/{playedTime}.json` respectively, and will create one `exports/overview-{timestamp}.json`.

But when using `s3s -i` to upload results, we need to provide a `results/overview.json` and a `coop_results/overview.json`.

I an curious how to get these two `overview.json`?

**Comment by zhxie** [comment]
Thanks. The error message confuses me a bit but I can now upload results successfully.

**Comment by zhxie** [comment]
```
Must pass in results/ or coop_results/ followed by an overview.json. Exiting.
```

It was my fault. I thought I needed to provide an overview.json for results and an overview.json for coop_results.

**Comment by frozenpandaman** [comment]
No problem. Thanks! Glad I could help!
