### ISSUE TITLE
Error during token generation

### ISSUE THREAD

**Issue by Sir-Mastermind** [frozenpandaman/s3s#135]
When I type the command `python3 s3s -M -r` it tries to generate tokens but crashes shortly after

**Comment by frozenpandaman** [comment]
Please paste the full output here.

**Comment by Sir-Mastermind** [comment]
python3 s3s.py -M -r
s3s v0.5.2
Blank token(s).
Attempting to generate new gtoken and bulletToken...
Error during f generation:
{
  "reason": "Something went wrong.",
  "error": true
}

**Comment by Sir-Mastermind** [comment]
oops. Didn't mean to close

**Comment by frozenpandaman** [comment]
`f` generation via the imink API is currently down:

https://status.imink.app/

**Comment by Sir-Mastermind** [comment]
So I just have to wait until it goes back up again?

**Comment by frozenpandaman** [comment]
Yep, or obtain your tokens manually.

**Comment by Sir-Mastermind** [comment]
Ok. Thank you very much for the quick reply ^^

**Comment by Banana9728** [comment]
> Yep, or obtain your tokens manually.

I'm having the same problem, if I don't want to wait, how would I put the tokens in manually?

**Comment by frozenpandaman** [comment]
The readme knows all. 🧙‍♂️

https://github.com/frozenpandaman/s3s#manual
