### ISSUE TITLE
Error during f generation

### ISSUE THREAD

**Issue by ranidspace** [frozenpandaman/s3s#137]
I think Nintendo may have changed something with the API as trying to run s3s gives me this error.
```
Attempting to generate new gtoken and bulletToken...
Error during f generation:
{
  "error": true,
  "reason": "Something went wrong."
}
```
A friend sent me this error and i checked and ran it like normal, and it happened to me as well.

**Comment by frozenpandaman** [comment]
The imink `f` generation API is currently down: https://status.imink.app/

@JoneWang will probably get it fixed shortly, as always.

**Comment by ranidspace** [comment]
Ah I see. GitHub hides issues that have already been closed I didn't see that this has happened before until after posting this

**Comment by frozenpandaman** [comment]
No worries! It's happened from time to time in the past, yeah.

When you click on the [Issues tab](https://github.com/frozenpandaman/s3s/issues) it only shows open issues by default – you need to click on "___ closed" to change the filter.

**Comment by frozenpandaman** [comment]
It's been fixed as of a couple hours ago, fwiw!
