### ISSUE TITLE
Can I use s3s to get the progress of my badges?

### ISSUE THREAD

**Issue by MeiKD957** [frozenpandaman/s3s#139]
I tried to view my badge progress with Lean's seed checker tools by exporting my profile from s3s to it. But it only contains the data of the latest 100 battles. For example, I have won more than 1000 with Crab Tank, but the website shows I haven't got the silver badges. (only 99 wins) 
So I would like to know if there are methods to know the progress of my badges.

**Comment by frozenpandaman** [comment]
No, your old battle history is deleted from Nintendo's servers after it disappears from the SplatNet app, unless you upload it to stat.ink with s3s.

**Comment by MeiKD957** [comment]
OK. Thank you very much!
