### ISSUE TITLE
Hey, is this safe to use?

### ISSUE THREAD

**Issue by bellis-ai** [frozenpandaman/s3s#147]
Seeing this thread here:

https://twitter.com/nintendo_cs/status/1702547829833810129

```We have confirmed the existence of unauthorized apps that are illegally accessing our servers and causing a load on "Splatoon 3". Use of such apps constitutes a violation of our Terms of Service, and upon confirmation of such use, we may take action such as suspending the use of the service. Please be aware of this.```

I'm wondering if there's a more aggressive policy being taken towards using tools like these. It's been pretty safe up to this point, I'm not sure if I should be worried or not.

**Comment by frozenpandaman** [comment]
#146
