### ISSUE TITLE
Test mode printing errors

### ISSUE THREAD

**Issue by butteredwaffles** [frozenpandaman/s3s#150]
Hello!

Wanted to ask if it was okay to open a small PR so that validation requests to the stat.ink API with `test=yes` print a successful validation message [according to the expected response](https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Battle-%EF%BC%8D-Post#successful-testyes) rather than bubbling down to the error code below.

**Comment by frozenpandaman** [comment]
@butteredwaffles Yes please!
