### ISSUE TITLE
Incomplete battle data

### ISSUE THREAD

**Issue by Twister2849** [frozenpandaman/s3s#151]
Hi!

So I uploaded all my files to stat.ink but I noticed that I only have 110 battles in my log. Now I’m 100% sure I’ve done more than 400 battles across all modes due to my badges in the actual game. The results in the log are very scattered and show few battles I’ve done this year and it just ends at February. I’ve run the command with the -r flag several times but it says I’ve uploaded all of my battles and jobs. So is there something wrong with the upload process or the commands?

**Comment by niyari** [comment]
![image](https://github.com/frozenpandaman/s3s/assets/2970321/ffd2b689-6770-4f82-ac34-2047f49c3ea2)
The situation varies depending on the timing of uploads using s3s. 
The images are screenshots from Splatnet3. 
We read the categories from A to E written on the images and upload them as play results.
In other words, if you launch s3s after playing 350 times in category B, it will retrieve the latest 50 play records (starting from the 300th play) and register them on statink.

**Comment by Twister2849** [comment]
I see. So everything works. There’s no way to get the records before the 301st one then I suppose.

**Comment by frozenpandaman** [comment]
Correct, you can only get the most recent 50 of each type (A, B, C, D, E) for a possible total of 350. After that the data is deleted from Nintendo's servers (presumably) so there's no way for us/you to access it.
