### ISSUE TITLE
Issues with updating s3s

### ISSUE THREAD

**Issue by KallMeQul** [frozenpandaman/s3s#154]
I've only been using s3s for a couple months and two updates for it have rolled out since - every time it happens s3s asks if i would like to update. however, inputting y or n wont do anything and git will not accept other commands. i can wait for hours and s3s won't update
i got through the first update by running git as administrator, but that solution doesnt seem to be working this time. 

not sure if this will help but worth mentioning that trying to close the git window while stuck in update limbo will open a prompt: 
> Processes are running in session:
> | WPID  PID  COMMAND
> | 6192  2039 C:\Users\name\AppData\Loca
> Close anyway?

if anyone has any ideas on how to help i would appreciate it!

**Comment by ghtz08** [comment]
In the command line, use the `cd` command to navigate to the root directory of the "s3s" project, and then execute the `git pull` command to manually update it. Check to see if any errors occur.

**Comment by frozenpandaman** [comment]
Happy to hear it! Auto-updating should work though... unfortunately I don't know that much about Windows, or your setup 😅

Is this just because it's trying to update while another instance (process) of it is running or something?

**Comment by KallMeQul** [comment]
i'm really not sure! i dont think multiple instances is the case at least - ive only ever had one of git open. unless there's a clone of it somewhere i haven't noticed XD 
i've looked all through task manager and firewall stuff trying to solve it myself (though that didnt yield any results) task manager didn't show me anything running with it. ive also tried only having s3s open and everything else (browser, discord, obs too) closed 
 
in regard to windows, it might be scuff because i dont actually have windows set up on my pc. it's not fully activated and havent paid for a license, but as far as the internet told me, that really only affects personilization options. 
if you need the pc specs i could probably give them to you once i figure out how to find it!
