### ISSUE TITLE
jobs keep failing to upload due to unknown special

### ISSUE THREAD

**Issue by g0dd0gg0** [frozenpandaman/s3s#160]
not sure what precisely is wrong here, but I've got multiple jobs for salmon run that just don't upload due to 'unknown special'
all the errors are some variation of this
![image](https://github.com/frozenpandaman/s3s/assets/44775360/ef588a24-ea47-44ed-9d68-b74df26238da)

**Comment by frozenpandaman** [comment]
Is your s3s up-to-date? Try running `git pull`.

Sorry, I didn't bump the version number so it hasn't automatically prompted people to do that yet...

**Comment by g0dd0gg0** [comment]
oh! I didn't know I could force an update like that - I've now done so and it's running fine now :3 thanks!

**Comment by frozenpandaman** [comment]
Glad to hear it! Sorry for the v0.6.0 delay, I'll get to it this weekend. :)

**Comment by frozenpandaman** [comment]
v0.6.0 is now out and all users should be prompted to update.
