### ISSUE TITLE
Make lowercase `-M` work

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#163]
Someone messaged me (please don't do this, open an issue here) saying that having to press the shift key every time they use the `-M` option is messing them up because they keep typing it wrong. Despite this being very funny, I do admit I have no idea why I made `-M` uppercase in splatnet2statink however many years ago now – it was probably an arbitrary choice and is a little unexpected/inconsistent, one could argue!

Filing this issue as a reminder to add in (silent) support for `-m` (if it's not too complicated/annoying to do with argparse). Just have it treat it as uppercase instead, in case users mistype it.

Could probably also support upper/lowercase being treated the same for all flags, frankly.

**Comment by niyari** [comment]
Low priority suggestion: Update README; For questions that require code changes, please ask on GitHub.

**Comment by frozenpandaman** [comment]
The readme already says "Have any questions, problems, or suggestions? Create an issue here or contact me on Twitter. Please do not raise issues via Discord."

Despite that, this person messaged me on Discord. Oh well.

**Comment by frozenpandaman** [comment]
Merged in 4d08f96
