### ISSUE TITLE
Requests module not found

### ISSUE THREAD

**Issue by Twister2849** [frozenpandaman/s3s#165]
So I was going to upload my data to splatnet and this traceback appeared:

`Traceback (most recent call last):
  File "/home/runner/SPLATOON-3/s3s/s3s.py", line 7, in <module>
    import argparse, base64, datetime, json, os, shutil, re, requests, sys, time, uuid
ModuleNotFoundError: No module named 'requests'`

I tried doing `pip install requests` and the error message persists. Is there something wrong with the environment?

**Comment by Twister2849** [comment]
Never mind, I accidentally installed Nix and after uninstalling it the command works now :]

**Comment by frozenpandaman** [comment]
Glad you solved it!
