### ISSUE TITLE
I can't generate a session_token for gtoken

### ISSUE THREAD

**Issue by Elizabeth055** [frozenpandaman/s3s#166]
Hi! Little help here, I don't know what must be wrong I ain't big on coding or having used Python before. I am a Splatoon fan and used all the other Leanny's features obtained all seeds so far. Just this particular data extraction for the badges I can't seem to work it out. 

Basically step 6. I Can't make it past it, I downloaded "Pyhthon 3" (Latest updated version) and Git as well, made sure all are the latest versions. I ran the first command on cmd , Generated the cd s3s, all created succesfully on cmd , seems every step goes right. Except when running the S3S with Python, indeed asks for the TokenAPI, I introuduce the Token I have in the website, and forward by confirming the EN language that I'm using for the game. But it doesn't take me to any URL of Nintendo or nothing at all just S3S automatically closes after confirming Language, and when re-run it just closes again in a fraction of second. And to get to introduce the APIToken again I have to re-do the path cd s3s so it doesn't close on me but It never seems to get me to website to do step 6. To generate the session_token.

**Comment by frozenpandaman** [comment]
>it doesn't take me to any URL

It doesn't automatically open your browser, you need to copy & paste the link in.

>when re-run it

How are you running the script? You don't run it just by double-clicking the file.

**Comment by Elizabeth055** [comment]
> > it doesn't take me to any URL
> 
> It doesn't automatically open your browser, you need to copy & paste the link in.
> 
> > when re-run it
> 
> How are you running the script? You don't run it just by double-clicking the file.

Didn't mean like browser opening up straight away, I meant it doesn't generate any URL or further text at all. It automatically closes up as pressing enter to confirm EN Language.

Well I do double-click  for opening s3s again and trying to see if it asks for "TokenAPI" again or any other sort of text/instruction, since it just closes after as said: confirming Language. should I run it in another way?

**Comment by frozenpandaman** [comment]
>Well I do double-click for opening s3s again

Again, this isn't how you run s3s. See https://github.com/frozenpandaman/s3s?tab=readme-ov-file#usage-
