### ISSUE TITLE
Make a stat.ink key not required for "--getseed"

### ISSUE THREAD

**Issue by ranidspace** [frozenpandaman/s3s#167]
During the export_seed_json function, stat.ink isn't used at all, and i've tested it and ran it properly with the api key set to "skip". People may want a quick command line way to get the gearseed file for the seed checker website, without having to set up a stat.ink account. I can make a pull request though I'm unsure if this could cause problems with something else

**Comment by frozenpandaman** [comment]
Thanks for the suggestion!
