### ISSUE TITLE
Error during f generation

### ISSUE THREAD

**Issue by InfiniteRizard** [frozenpandaman/s3s#170]
![image](https://github.com/frozenpandaman/s3s/assets/129249574/f3f8b320-fa58-4528-a099-3031c2291660)

I'm unable to generate a new token, after I updated to v0.6.1
It was able to in v0.6.0

**Comment by frozenpandaman** [comment]
https://status.imink.app/

**Comment by frozenpandaman** [comment]
Seems to be back up now.
