### ISSUE TITLE
Can't login (The provided session_token_code is invalid)

### ISSUE THREAD

**Issue by paul-sama** [frozenpandaman/s3s#174]
get_session_token error

https://accounts.nintendo.com/connect/1.0.0/api/session_token

return
{"error_description":"The provided session_token_code is invalid","error":"invalid_request"}

**Comment by frozenpandaman** [comment]
OK, I have no clue why the regex (suddenly??? why now???) started capturing the wrong `session_token_code` value from the URL, thus leading to this error… honestly, so confused why this issue popped up now, never before, unless some default behavior in `re` parsing changed or whatnot… truly bizarre unless I'm just totally overlooking something… Anyway, it was a 1 character fix, lol. Thanks for the heads up!

**Comment by frozenpandaman** [comment]
OK, making more sense now... looks like Nintendo changed the URL structure on the connect/1.0.0/authorize page, specifically the ordering of the parameters. This is the URL provided when you right-click "Select this account" and paste it into s3s:

Old: `npf71b963c1b7b6d119://auth#state=blah&session_token_code=jsonwebtoken&session_state=blahblah`

New: `npf71b963c1b7b6d119://auth#session_token_code=jsonwebtoken&state=blah&session_state=blahblah`

Which broke our regex parsing of this string 😅
