### ISSUE TITLE
python not being recognized as installed

### ISSUE THREAD

**Issue by GoomySpl** [frozenpandaman/s3s#177]
hello, when i get to step 4 of the setup guide, I put in the python -m pip command into cmd. however, i get an error saying "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings." I am sure that I have python installed, so what should i do?

**Comment by niyari** [comment]
https://learn.microsoft.com/en-us/windows/python/faqs#python-exe--------microsoft-store------------

**Comment by frozenpandaman** [comment]
Thanks for helping this user out, @niyari.

I don't use Windows and can't really help here. I'm confident Google can solve your troubles!

**Comment by GoomySpl** [comment]
literally forgot that i posted this, but thank you!
