### ISSUE TITLE
CoopHistoryDetailQuery may have changed?

### ISSUE THREAD

**Issue by sergeant-wizard** [frozenpandaman/s3s#178]
Hi, great project!

After today's splatoon 3 update to 7.2.0, I started getting errors from s3s:

```
python s3s.py -t -osr
s3s v0.6.4
Note: This is an atypical way to run the script for manually specifying the number of recent Salmon Run jobs to upload. All 50 recent jobs can be uploaded automatically by appending the -r flag.

Number of recent jobs to upload (0-50)? 1

Pulling data from online...
Validating your tokens... done.

Error uploading one of your battles. Please try running s3s again.
```

I noticed that the graphql request [here](https://github.com/frozenpandaman/s3s/blob/410bd92f822b17a39ca50e2e25efe1a04c9d2fc1/s3s.py#L1397) is returning  error 400.

I compared the request with the canonical request, and it turns out that the sha256 for `CoopHistoryDetailQuery` has changed from
`824a1e22c4ad4eece7ad94a9a0343ecd76784be4f77d8f6f563c165afc8cf602` to `42262d241291d7324649e21413b29da88c0314387d8fdf5f6637a2d9d29954ae`.

I checked that the error is resolved with [this commit](https://github.com/sergeant-wizard/s3s/commit/1f2c3dfbb69bbfe927455d4da0bbac1ad45e1ce9).

I don't know what else has changed, but it seems like at least `CoopHistoryDetailQuery` has.

**Comment by frozenpandaman** [comment]
Hey, thanks for the catch! So apparently this query actually got updated with ver. e135295b of SplatNet  back in November and I just didn't notice… and this update deprecated the old one. Fixed! Appreciated!
