### ISSUE TITLE
"ModuleNotFoundError: No module named 'requests'" when trying to run s3s

### ISSUE THREAD

**Issue by CursedElectric** [frozenpandaman/s3s#179]
When trying to run any command on s3s it results with this error(in attached). I can give more info if needed!
![image](https://github.com/frozenpandaman/s3s/assets/95328176/557b696e-aa5a-4799-9e5f-37d57885dd16)

**Comment by frozenpandaman** [comment]
Did you install the required libraries? Step 4 of the readme.

**Comment by CursedElectric** [comment]
oops yes that fixed it. I've been using this program for months but a friend recently wanted to use it as well. I must've messed it up when I reinstalled python while telling them how to install it. thanks for the swift response!!
