### ISSUE TITLE
Endpoint of the Summery Stats in SplatNet3

### ISSUE THREAD

**Issue by Voroniyx** [frozenpandaman/s3s#18]
Hey, I have a question about the endpoint of the [Summery Page](https://api.lp1.av5ja.srv.nintendo.net/history_record/summary) in SplatNet3. Does anyone know the endpoint, i.e. the URL, or is that not stored in json like the stats in Splatnet2?

**Comment by clovervidia** [comment]
You can get that page's data if you make a GraphQL request with request ID `f8ae00773cc412a50dd41a6d9a159ddd`.
