### ISSUE TITLE
Nintendo Membership required error

### ISSUE THREAD

**Issue by BreadRyder** [frozenpandaman/s3s#180]
While trying to generate gtoken and bullet token, I encountered an error regarding Nintendo Membership. I currently have Nintendo Online and have logged in on both my Switch and my laptop.

`s3s v0.6.5 Blank token(s). Attempting to generate new gtoken and bulletToken... Error from Nintendo (in Game/GetWebServiceToken step): { "status": 9450, "errorMessage": "Membership required error.", "correlationId": "3a8183f7-2386e8f3" }`

**Comment by frozenpandaman** [comment]
OP let me know sepa

**Comment by frozenpandaman** [comment]
OP let me know separately that they were accidentally using a different account without an NSO subscription, which makes sense here. Glad you solved it!

(Whoops accidentally hit the wrong button to reopen this instead of commenting...)
