### ISSUE TITLE
f token generation error

### ISSUE THREAD

**Issue by wonderbrian** [frozenpandaman/s3s#181]
Don't see any errors with https://status.imink.app

This is a fresh install on a new device

```
$ python s3s.py -r
Generating new config file.
s3s v0.6.5
stat.ink API key: [redacted]
Default locale is en-US. Press Enter to accept, or enter your own (see readme for list).

Blank token(s).          
Please log in to your Nintendo Account to obtain your session_token.

Make sure you have read the "Token generation" section of the readme before proceeding. To manually input your tokens instead, enter "skip" at the prompt below.

Navigate to this URL in your browser:
[redacted]
Log in, right click the "Select this account" button, copy the link address, and paste it below:
[redacted]

Wrote session_token to config.txt.
Attempting to generate new gtoken and bulletToken...
Error during f generation:
{
  "reason": "Something went wrong.",
  "error": true
}```

**Comment by Scro-mx** [comment]
I have the same concern for my side

`s3s v0.6.5
Validating your tokens...

The stored tokens have expired.
Attempting to generate new gtoken and bulletToken...
Error during f generation:
{
  "reason": "Something went wrong.",
  "error": true
}`

**Comment by tugofwardolphin52** [comment]
I'm also having this same issue for the last 9 hours. I've been checking the site's status and it hasn't indicated that anything was down.

**Comment by Awia001** [comment]
For whatever reason, the api call in `call_f_api` is returning a 500 at the moment. The actual error you're seeing is a KeyError raised by the this section of code in iksm.py:490
```python
api_response = requests.post(f_gen_url, data=json.dumps(api_body), headers=api_head)
resp = json.loads(api_response.text)

f = resp["f"]
```
The phone app is still working for me so it's possible Nintendo have altered the api flow?

**Comment by frozenpandaman** [comment]
It's been fixed (as of a few hours ago!)
