### ISSUE TITLE
Error in uploading salmon run records for the new season

### ISSUE THREAD

**Issue by Bacongitgit** [frozenpandaman/s3s#182]
Error uploading job. (ID: SOME ID etc.)
Message from server:
{
    "error": {
        "players": "uniform: Uniform is invalid."
    }
}

**Comment by frozenpandaman** [comment]
cc @fetus-hina

**Comment by fetus-hina** [comment]
Probably fixed

**Comment by frozenpandaman** [comment]
Thanks, yay!
