### ISSUE TITLE
Error when uploading matches with the new King Salmon (The Triumvirate)

### ISSUE THREAD

**Issue by InfiniteRizard** [frozenpandaman/s3s#184]
I knew it might gonna happen, but here is the issue anyway for tracking, so it is hopefully fixed soon ^^

![image](https://github.com/frozenpandaman/s3s/assets/129249574/75a35623-d70d-4bce-8145-305a3b923486)

**Comment by frozenpandaman** [comment]
#183 

Run `git pull` (to update s3s)

**Comment by frozenpandaman** [comment]
Now fixed on stat.ink's end (no update necessary)
