### ISSUE TITLE
issue with step 6, generating tokens

### ISSUE THREAD

**Issue by poshzhongda** [frozenpandaman/s3s#185]
hi, i have been following this guide and the last step i completed was entering my api key in s3s python thingy, imediately after this, i hit enter, a config txt was formed but with no values for the tokens, and the s3d python did not prompt me to go to nintendo.com or do any steps to generate values, im confused idk what i did wrong and would like some help. every time i try to open s3s python, it immediately closes

**Comment by frozenpandaman** [comment]
How are you running the program? Are you double clicking on the .py file by chance?

**Comment by poshzhongda** [comment]
yes, i double click, the file opens, then immediately closes after a few seconds

**Comment by frozenpandaman** [comment]
Double clicking isn't how you're supposed to run the program – the readme never says to double click on it. :)

See the "Usage" section of the readme.

**Comment by poshzhongda** [comment]
hi, i still dont understand what you mean, step 6 says it should give me instructions to go to nitendo website, i didnt receive these instruction, and i understand the usage section but it doesnt say where to implement these commands

**Comment by frozenpandaman** [comment]
You run the script by typing `python s3s.py` into a terminal window, not by double clicking an icon.

**Comment by poshzhongda** [comment]
hi sorry again, but what is the format for entering the commands, i did what u asked above but it said to specifiy whether i want to uplaod battles or salmon run, i just want the instruction to obtain my session token

**Comment by frozenpandaman** [comment]
https://github.com/frozenpandaman/s3s#usage-

https://github.com/frozenpandaman/s3s#tips-for-using-s3s
