### ISSUE TITLE
An error while generating the token

### ISSUE THREAD

**Issue by Bacongitgit** [frozenpandaman/s3s#186]
Error from Nintendo (in Account/Login step):
{
  "status": 9427,
  "errorMessage": "Upgrade required.",
  "correlationId": "22912fa6-0011c2ff"
}

**Comment by samuelthomas2774** [comment]
> Should we re-do our login from the NSO website for new tokens or is there a script update that will fix this?

There's nothing you can do currently. This is happening because the f generation API doesn't support 2.10.1 yet. I am working on updating my API, once it's working you can switch to that or just wait for the imink API to be updated as well.

**Comment by timeimp** [comment]
Thought so. 

I just checked the f generator API status and it's showing issues 😞 

Thanks @frozenpandaman !

**Comment by frozenpandaman** [comment]
Looks like @samuelthomas2774 has just updated nxapi-znca-api, so switching to that one now works, following instructions here: https://github.com/frozenpandaman/s3s/issues/181#issuecomment-2136317459

I alerted Jone as well so I assume the imink API will be updated shortly as well.

**Comment by sophisticated-stoner** [comment]
Should we switch back immediately once imink is updated again? 

https://status.imink.app/

**Comment by frozenpandaman** [comment]
@sophisticated-stoner Up to you. They're just alternatives to each other, providing essentially the same exact service. s3s is set up to use imink as a default as it's been around longer.

(Speaking of which, I'm glad I don't have to host the API myself anymore... and/or rely on the old-old flapg one... 😅)

**Comment by frozenpandaman** [comment]
The imink API is now updated & back to working.
