### ISSUE TITLE
Support Conch Clash

### ISSUE THREAD

**Issue by mad-p** [frozenpandaman/s3s#188]
From Summer Fest 2024, a new fest mode Conch Clash is introduced.
New `dragonMatchType` are:

- `CONCH_SHELL_SCRAMBLE` (ホラガイ争奪戦 1x)
- `CONCH_SHELL_SCRAMBLE_10` 10x
- unknown 33x

See also fetus-hina/stat.ink#1324

**Comment by frozenpandaman** [comment]
Thanks! I haven't been playing so wasn't aware of this change. Looks like it's just a new/official name for mirror matches? https://splatoonwiki.org/wiki/Splatfest#Conch_Clash

When stat.ink supports these (cc @fetus-hina) I'll make sure it's supported here too. :)

Looks like there's no errors for now, at least, just no data being sent.

**Comment by mad-p** [comment]
10x conch clash has
`"dragonMatchType":"CONCH_SHELL_SCRAMBLE_10"`
I guess 33x is "CONCH_SHELL_SCRAMBLE_33".

**Comment by frozenpandaman** [comment]
@mad-p Thanks! I'm traveling now and am away from my computer for another week. If you (or others) want to submit this as a PR I'll gladly merge it!
