### ISSUE TITLE
Using -i flag returns contradictory results

### ISSUE THREAD

**Issue by VGmaster670** [frozenpandaman/s3s#19]
not sure if this is intentional since stat.ink doesn't support splat 3 yet (making an issue anyways just in case it isn't) but attempting to use the -i flag will return an error regardless of if you use an argument or not
`PS C:\Users\[User]\3D Objects\s3s> python s3s.py -i
s3s v0.0.4
While s3s is in alpha, please update the script regularly via "git pull".
usage: s3s.py [-h] [-M [N]] [-r] [-nsr] [-osr] [--blackout] [-t]
s3s.py: error: argument -i: expected one argument
PS C:\Users\[User]\3D Objects\s3s> python s3s.py -i overview.json
s3s v0.0.4
While s3s is in alpha, please update the script regularly via "git pull".
Cannot use -i with other arguments. Exiting.`

**Comment by frozenpandaman** [comment]
`-i` isn't yet implemented, since stat.ink doesn't accept uploads at this time. :)
