### ISSUE TITLE
Set-up issue at step 5/6

### ISSUE THREAD

**Issue by yoshido8** [frozenpandaman/s3s#192]
I'm stuck at step 5/6. [I am running on Windows 10 by the way]
I learned not to double-click the python in the s3s folder and to run off the command prompt (I think), but I'm trying to run the script and put in my API key from stat.ink. Looking at usage doesn't really help but I think that's because I don't know how python works really and I don't know how to run the script. A side note is that when I got to step 4, I used `pip install -r requirements.txt` instead of `python -m pip` since the first one worked while the second one didn't. My main problem is when I try to enter stuff like `-r` or `python s3s.py -r -M` or anything similar. I get the same thing back every time: "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases."

I did make sure to check the option during setup to add it to PATH, but now I'm just unsure how to keep going. Also, for later on, I want to run off Automatic via [nxapi-znca-api] since I already had that installed and working a long time ago.

**Comment by frozenpandaman** [comment]
Hi @yoshido8, thanks for giving it a shot! I don't use Windows and am really not sure how to best help at this step, but I can try. It's odd that you indeed ran the Python.org installer (you said you added it to your PATH too, which should make the `python` command recognized) but then it's not recognizing the command. Did you restart your computer after?

If that still doesn't work, I'd say that installing Python via the Microsoft Store should probably work too – it doesn't really matter how you get it, you just need it installed. So do what the message there says, run `python` just plain (without arguments or any other words after it) and see if that works. Another restart may be required.

After that, try running `python --version` which should verify if you've successfully installed it or not. Once you have, you should be able to install the required libraries (should be simple) and run the script!

**Comment by yoshido8** [comment]
So I ran the command `python` and it just opened up the Microsoft store with Python there. I just decided to get python from the Microsoft store and then when I entered the code `python -m pip` I get a wall of commands and general options but nothing about my stat.ink API token. I tried then putting in `-r` which gave me: '-r' is not recognized as an internal or external command,
operable program or batch file." I then tried python `s3s.py -r -M` which just gave me back:```

Traceback (most recent call last):
  File "C:\Users\_name_\s3s\s3s.py", line 10, in <module>
    import requests, msgpack ModuleNotFoundError: No module named 'requests'
```

I tried using `--help` but that also came back with: ```
'--help' is not recognized as an internal or external command,
operable program or batch file.
```

I am making progress though with it now at least giving me prompts, I guess

**Comment by frozenpandaman** [comment]
@yoshido8 Looks like Python is installed now, yep! Try the `python -m pip install -r requirements.txt` command again, or alternatively just `pip install -r requirements.txt`. (This is what installs the "requests" module which your error message is about.)

**Comment by yoshido8** [comment]
Alright, I got everything to work, and my starts are uploading! Thanks for the help!

**Comment by frozenpandaman** [comment]
Nice! Happy to hear it!
