### ISSUE TITLE
Automatic Token Generation Issue

### ISSUE THREAD

**Issue by mahimeghan** [frozenpandaman/s3s#194]
Hello.

I have been using s3s for a few weeks now, but when attempting to upload some recently played battles the script says it is unable to create a token. I even deleted all the files and reinstalled to no avail.

![image](https://github.com/user-attachments/assets/12764de6-6139-46bc-ae37-8c231b98a5dd)

[Here](https://stat.ink/@mahimeghan) is my stat.ink account, if that is needed for whatever reason.

**Comment by frozenpandaman** [comment]
Seems the imink API is down right now: https://status.imink.app/

**Comment by ADeeeee** [comment]
BTW
Does an automatically failover sound good?

**Comment by frozenpandaman** [comment]
@ADeeeee Not sure what this means.

**Comment by ADeeeee** [comment]
@frozenpandaman 
According to https://github.com/frozenpandaman/s3s/issues/181#issuecomment-2136317459

There's another exsiting f-api from nxapi and we could replace the default one manually in the config, so what if we build them both in the script and make it try to failover while one of them is down?

**Comment by mahimeghan** [comment]
> Seems the imink API is down right now: https://status.imink.app/

Ohh, okay. Thought it was on my end. Will try again later.

**Comment by frozenpandaman** [comment]
@ADeeeee Ah, you mean to have a fallback to a secondary provider. It's possible, but frankly it's a lot easier to just store a single value in `config.txt` and I don't know if I want to change that at this point. Jone is pretty fast at getting imink back up + working when it goes down. People can always replace the URL themselves as well if they _need_ an immediate workaround.

**Comment by frozenpandaman** [comment]
@mahimeghan Fixed (a little over an hour ago)!

**Comment by ADeeeee** [comment]
@frozenpandaman You're right, pardon me for the inaccurate keyword.

The priority is pretty low, but it's easier to know how the situation going on, for instance:
* s3s working
    * All UP
    * imink down or nxapi down (No errors, no issues)
* s3s not working with error
    * Fallbacked, both down (Problem shoude be on nintendo's side, rarely both f APIs are broken though)

I could take a look if this behavior is helpful.
