### ISSUE TITLE
Can't open file - no file in directory

### ISSUE THREAD

**Issue by KOTheRipper** [frozenpandaman/s3s#197]
New to github, when doing the first time run after setup i entered my api token from stat.ink and it never took me to the nintendo website.

I closed git and tried redoing the steps outlined and it gave me a fatal error on trying to clone, and it cannot find the main directory using cd s3s/

**Comment by frozenpandaman** [comment]
>when doing the first time run after setup i entered my api token from stat.ink and it never took me to the nintendo website.

It doesn't take you there automatically.
```
Navigate to this URL in your browser:
[...]
Log in, right click the "Select this account" button, copy the link address, and paste it below:
```

>tried redoing the steps outlined and it gave me a fatal error on trying to clone
"Clone" just means "make a copy of this on my computer", aka download it. You already downloaded the code and everything, you just need to run the script again.

**Comment by KOTheRipper** [comment]
Trying to run the script again "$ python s3s.py -r" I get two errors. Can't open file and No such file or directory.

"You will then be asked to navigate to a specific URL on Nintendo.com, log in, and follow simple instructions to obtain your session_token; this will be used to generate a gtoken and bulletToken."

>I am confused what is the specific url to use

**Comment by frozenpandaman** [comment]
>"$ python s3s.py -r"

You don't type the `$`, that's just to indicate the start of the line of input.

>I am confused what is the specific url to use. 

It's what I quoted in my above reply. If you run `python s3s.py -r` it should prompt you first to enter your stat.ink key (which you said it already did, meaning you ran it once correctly already?), then choose your language, then log in to your account, like this:
<img width="380" alt="image" src="https://github.com/user-attachments/assets/d38b2c32-74ce-462e-8cc6-8093bb1d99fe">

**Comment by KOTheRipper** [comment]
> You don't type the `$`, that's just to indicate the start of the line of input.
ok, i understand that I was just demonstrating what I was typing. Using that command. I get "can't open file" [Errno 2] no such file in directory*
> > I am confused what is the specific url to use.
> It's what I quoted in my above reply. If you run `python s3s.py -r` it should prompt you first to enter your stat.ink key (which you said it already did, meaning you ran it once correctly already?), then choose your language, then log in to your account, like this: <img alt="image" width="380" src="https://private-user-images.githubusercontent.com/7245874/382059208-d38b2c32-74ce-462e-8cc6-8093bb1d99fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTY5MTgsIm5iZiI6MTczMDM5NjYxOCwicGF0aCI6Ii83MjQ1ODc0LzM4MjA1OTIwOC1kMzhiMmMzMi03NGNlLTQ2MmUtOGNjNi04MDkzYmIxZDk5ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMTc0MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODEyZTAxYWUzMWM0NTVhNmY1YmJmMmNmZjk0ZDA3NGMzNGRkMDQ2OGE3MzEzZDE0NjA2NTcxOTY4OTFhYzY2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.grdtJZtqBy6FkQrhwFriMeBPqeM8asQw49COh0QK434">

After entering the stat.ink key it didn't do anything else that's why i was confused but now i can't even run the command

**Comment by frozenpandaman** [comment]
You're typing in the command to run the script, not clicking on it, yes?

Screenshots would help.

**Comment by KOTheRipper** [comment]
![image](https://github.com/user-attachments/assets/c19f07ce-f511-4b9a-9339-634cd4ed7575)

As far as I understand yes I am.

**Comment by niyari** [comment]
Why are you using MINGW64?

**Comment by KOTheRipper** [comment]
> Why are you using MINGW64?

That's just what pops up when I open Git Bash. I don't even understand what MINGW64 is.

Is there something else I should be using? All I did was download Git as per the instructions and got stuck after entering my stat.ink key

**Comment by frozenpandaman** [comment]
Don't use Git Bash. Per the readme, you should be using PowerShell or Command Prompt (cmd) which are what's built into Windows.

**Comment by KOTheRipper** [comment]
> Don't use Git Bash. Per the readme, you should be using PowerShell or Command Prompt (cmd) which are what's built into Windows.

Oh my mistake then, so for Command Prompt then what command am I using to run the script?

![image](https://github.com/user-attachments/assets/3fb0b9ec-3030-4e35-9f7a-895b98844a37)

**Comment by frozenpandaman** [comment]
The part on the left, before the `>` on each line, shows me you're just in your user directory. But the s3s script isn't downloaded to there.

You need to **c**hangr **d**directory to the `s3s/` folder:
```
cd s3s/
```
Which is mentioned in step 4 :)

**Comment by KOTheRipper** [comment]
> The part on the left, before the `>` on each line, shows me you're just in your user directory. But the s3s script isn't downloaded to there.
> 
> You need to **c**hange **d**irectory to the `s3s/` folder:
> 
> ```
> cd s3s/
> ```
> 
> Which is mentioned in step 4 :)

ok that worked, thank you!
