### ISSUE TITLE
NSO app gives error?

### ISSUE THREAD

**Issue by JippC** [frozenpandaman/s3s#21]
After I run mitmweb and setup the proxy on my phone, when I try to use the NSO app it continually gives me the following message:

Please Check
Please sign in to your Nintendo Account again.
Error Code: 2817-0199
(Sign Out)

If I sign out then sign back in again it gives me the same screen. I can't even get to the page where I have the option to access the Splatnet stuff

Edit: I was able to get the automatic method working instead of manual. Not sure why this was happening though.

**Comment by frozenpandaman** [comment]
Seems as if the proxy isn't set up & running correctly, or isn't installed on the root level properly.

Does Chrome open properly without the "No internet connection" banner, and can you load webpages?

**Comment by frozenpandaman** [comment]
Yep, automatic works and is a lot easier – recommended for most users. :)

**Comment by dogey11** [comment]
@JippC was this on android by chance? I got the same error on android 10, to which I found mitmproxy won't work with the switch online app on android 7 and up (which is basically every unrooted android made in the last 5 years).

**Comment by frozenpandaman** [comment]
@dogey11 mitmproxy will work on _any_ version of Android as long as the certificate is installed at the root level:

https://github.com/frozenpandaman/s3s/wiki/mitmproxy-instructions
