### ISSUE TITLE
ANSI codes showing instead of formatted text

### ISSUE THREAD

**Issue by guigas7** [frozenpandaman/s3s#25]
I'm getting things like "←[91m" between the text that look like ANSI escape codes. I'm using Widnows 10 Power Shell, and it never happend before this new version.

![image](https://user-images.githubusercontent.com/11247506/192169554-764f0b05-52b6-40ab-be4a-7fc15df56c50.png)

**Comment by frozenpandaman** [comment]
Oof, Windows doesn't support those? I'm on Mac.

@clovervidia uses Windows, so maybe he has a solution to get this working? (Trying to do basic colors & formatting.) Thanks for the heads up!

**Comment by frozenpandaman** [comment]
Fixed in a45599a.
