### ISSUE TITLE
KeyError: 'vsHistoryDetail'

### ISSUE THREAD

**Issue by imaginationac** [frozenpandaman/s3s#27]
Might be related to #26 
Using v 0.1.1

When trying to import to stat.ink some local results, I get the following output.
![image](https://user-images.githubusercontent.com/424106/192190275-49fac41d-17f0-424e-8604-203e9a7f1802.png)

```
python.exe .\s3s.py -i .\export-1663699790\overview.json .\export-1663699790\results.json
s3s v0.1.1
» While s3s is in beta, please update the script regularly via `git pull`.

Traceback (most recent call last):
  File "C:\Users\Dorian\Projects\s3s\s3s.py", line 1173, in <module>
    main()
  File "C:\Users\Dorian\Projects\s3s\s3s.py", line 1119, in main
    if battle["data"]["vsHistoryDetail"] != None:
KeyError: 'vsHistoryDetail'
```
The two JSON files are in the attached archive for reference.
[export-1663699790.zip](https://github.com/frozenpandaman/s3s/files/9642800/export-1663699790.zip)

This isn't the case for all my results as I was able to successfully import at least one set.

**Comment by frozenpandaman** [comment]
You need to pass in `results.json` as the first file – opposite order from what you have. :)

i.e. `python s3s.py -i results.json overview.json`

I'll add a nicer way to handle this error, though, in the case people reverse them. Thanks!
