### ISSUE TITLE
Exporting without sorting coop_results.json

### ISSUE THREAD

**Issue by AXU9513** [frozenpandaman/s3s#28]
Hello,

I'm getting a warning when exporting data to local json files: `(!) Exporting without sorting coop_results.json` 

I guess it has something to do with the following code in `s3s.py`:
```
if needs_sorted: # put regular, bankara, and private in order, since they were exported in sequential chunks
    try:
        ink_list = [x for x in ink_list if x['data']['vsHistoryDetail'] != None] # just in case
        ink_list = sorted(ink_list, key=lambda d: d['data']['vsHistoryDetail']['playedTime'])
    except:
        print("(!) Exporting without sorting results.json")
    try:
        salmon_list = [x for x in salmon_list if x['data']['vsHistoryDetail'] != None]
        salmon_list = sorted(salmon_list, key=lambda d: d['data']['coopHistoryDetail']['playedTime'])
    except:
        print("(!) Exporting without sorting coop_results.json")
```

In the second `try` which sort the salmon run list, should it be `x['data']['coopHistoryDetail'] != None` instead of `vsHistoryDetail `?

**Comment by frozenpandaman** [comment]
Whoops, thanks for the catch. You're right. Fixed now. :)

**Comment by frozenpandaman** [comment]
Though I also don't think the Salmon Run data actually needs any sorting… since there aren't multiple screens/modes or anything. So your exported files should still all be fine. :D If you choose to run it again and it _doesn't_ give identical output, let me know, I'd be interested!

**Comment by AXU9513** [comment]
Sure I agree with you.

**Comment by frozenpandaman** [comment]
@AXU9513 Makes sense. In that case a `reverse()` function may be a tiny bit cheaper/faster than `sorted()` but I don't think it's too big of an issue and it's consistent this way.
