### ISSUE TITLE
weird looping issue for some people and/or 9403 invalid token error

### ISSUE THREAD

**Issue by qjzcj2008** [frozenpandaman/s3s#3]
Seems only I got this problem, I'll go to check my configuration and try it later or just change to another way to get my token. XD

~~It seems that I can't intercept the NSO app's web traffic anymore via MITM after updated to the `2.2.0` version on my IOS device, only get `Connection Error` with the error code `2816-0598`, with the same configuration I can intercept other apps' web traffic or the old version(`1.11.0`) NSO app's web traffic (of course only get `Update Required`), so I don't think my configuration goes wrong. I guess Nintendo may have done something to the app in the new version to prevent MITM attack.~~
~~Maybe now IOS devices isn't a good option for getting token manually. This is the situation I met here. Wonder if anyone would like to test it on their IOS devices to find out whether the NSO app now can't be MITM simply.~~

Also, I see the requirement in Google Play says the system version needs to be Android 6.0 or higher for the NSO app of the latest version `2.2.0` for now. Maybe the Wiki page for manually get token needs some updates?

**Comment by frozenpandaman** [comment]
>It seems that I can't intercept the NSO app's web traffic anymore via MITM after updated to the `2.2.0` version on my IOS device [...] I guess Nintendo may have done something to the app in the new version to prevent MITM attack.

Could be! I know next to nothing about iOS – perhaps that version (or a recent update on Apple's end?) added increased protection against custom certificates. Thanks for the info! @samuelthomas2774 would you happen to know anything about this?

>I see the requirement in Google Play says the system version needs to be Android 6.0 or higher for the NSO app

Thanks, whoops! I'll update that.

But yup, the best way is definitely using the Android Studio emulator on your computer, imo. :) Then you can use any (recent) Android version you want.

**Comment by paul-sama** [comment]
manually get token not work here.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/350651/189477625-aa754345-1505-4ac5-be95-b9259aa2bf58.png">

gtoken and bulletToken dislocation

automatic token generation not work either.
<img width="275" alt="image" src="https://user-images.githubusercontent.com/350651/189477703-1d58515a-6e36-4a2f-8fe9-8951eb6ccaa5.png">


and I can get token manual with MITM on iOS NSO `2.2.0`

**Comment by frozenpandaman** [comment]
@paul-sama The "124" is a typo on my end and will be fixed very soon!

For automatic token generation, that's an issue happening with some accounts. I _think_ I've solved it, and will update the repo when I get home shortly. For now, just run the script again _without_ deleting `config.txt` (contrary to what it says).

**Comment by slushiegoose** [comment]
> Could be! I know next to nothing about iOS – perhaps that version (or a recent update on Apple's end?) added increased protection against custom certificates. Thanks for the info! @samuelthomas2774 would you happen to know anything about this? 

I use iOS and I can mitmproxy fine on 2.2.0 - I can get the tokens there from anything

> For automatic token generation, that's an issue happening with some accounts. I think I've solved it, and will update the repo when I get home shortly. For now, just run the script again without deleting config.txt (contrary to what it says) and that should make it work!

I also DMed you on discord for a possible fix to this if you're still stuck!

**Comment by frozenpandaman** [comment]
@paul-sama The manual token entry issue has now been fixed: d0d11e4
I had switched the "926" and "124" values… hehe 😅

**Comment by frozenpandaman** [comment]
re-titling this discussion cuz it sort of morphed into two-issues-in-one :)

**Comment by samuelthomas2774** [comment]
> Could be! I know next to nothing about iOS – perhaps that version (or a recent update on Apple's end?) added increased protection against custom certificates. Thanks for the info! @samuelthomas2774 would you happen to know anything about this?

I'm still able to MITM the app on iOS, I'm using [Proxyman](https://proxyman.io) and [Proxyman for iOS](https://proxyman.io/ios). I did notice that if the proxy server hostname is a multicast DNS name it doesn't work (maybe because I didn't give the app local network access and something in the app tries to resolve it itself?).

> @paul-sama The manual token entry issue has now been fixed: [d0d11e4](https://github.com/frozenpandaman/s3s/commit/d0d11e4ca0efbdf3809485e40b27780ef03684bb)
> I had switched the "926" and "124" values… hehe 😅

@frozenpandaman Those values are base64/partly base64url encoded, the length might sometimes be slightly different.

**Comment by frozenpandaman** [comment]
@paul-sama The `9403: Invalid token.` error is now fixed too: f586576

**Comment by frozenpandaman** [comment]
My brain is absolutely fried right now (and also apparently I understood Python's new f-strings less well than I thought) so thank you a ton to @slushiegoose for helping me solve this!!!

Everything should be solved now… but feel free to comment or open up another issue if anyone runs into any errors. :)
