### ISSUE TITLE
kill / assist count

### ISSUE THREAD

**Issue by paul-sama** [frozenpandaman/s3s#30]
kill and assist count seem different between splatoon2 and splatoon3
sp2: kill = kill ，assist = assist
sp3: kill = kill + assist ， assist = assist

**Comment by frozenpandaman** [comment]
Are you talking about in-game or SplatNet? Both games show "kills + assists" as the stat on the in-game scoreboard.

You're right that on SplatNet 2, it displayed as "kills+assists (assists)" and now in SplatNet 3 it is displayed as "kills <assists>". But I think the numbers are sent to stat.ink correctly:

https://github.com/frozenpandaman/s3s/blob/e14cd3187f24dcc63999db3c530e346a99bf1037/s3s.py#L470-L472

**Comment by paul-sama** [comment]
I think is stat.ink bug
![image](https://user-images.githubusercontent.com/350651/192406958-8cb13b3b-8d39-453d-bec3-51ec3fbaf52d.png)
![image](https://user-images.githubusercontent.com/350651/192407025-4c0ae36f-33a4-4107-b6cc-f36ff2dcae4a.png)
NSO app show x11<4>

**Comment by frozenpandaman** [comment]
Interesting. Do you happen to have the exported JSON file that includes that battle, just so I can double check? If it was in your most recent 50 ones played, you can just run s3s with `-o` and post the `results.json` that it spits out here.

**Comment by paul-sama** [comment]
`"result": {
              "kill": 11,
              "death": 14,
              "assist": 4,
              "special": 1,
              "noroshiTry": null
            }`

**Comment by frozenpandaman** [comment]
I agree, it looks like a stat.ink display issue.

cc @fetus-hina

**Comment by frozenpandaman** [comment]
@paul-sama I think I was just misunderstanding, and then wasn't thinking clearly (addition is hard for middle-of-the-day eli, I guess…)

Everything looks correct.

That battle shows 11 kills, 4 assists
11 + 4 = 15 "kill or assist"s

**Comment by paul-sama** [comment]
15 is correct count?
![image](https://user-images.githubusercontent.com/350651/192445703-fee2ad06-69b7-44a1-b2ec-68c90f1c69a6.png)

**Comment by frozenpandaman** [comment]
oh my GOD you're right.

`player["result"]["kill"]` is really kills + assists 🤦 nice job nintendo.........

thank you SO much for pointing this out

**Comment by fetus-hina** [comment]
We disscussed about this issue in our dev Discord.

- Eli will release s3s which fixes this problem.
- Already registered data will be automatically corrected on the stat.ink side.

**Comment by frozenpandaman** [comment]
Fixed in 63b8231! Thanks again so much @paul-sama and sorry again for all the trouble I had in understanding this at first. Very grateful to have this pointed out.

And thank you Hina for fixing the already-uploaded-to-the-site battles. 🙏

**Comment by fetus-hina** [comment]
Sorry for the delay, but the correction of the data registered in the past has been completed. (https://github.com/fetus-hina/stat.ink/issues/1088)
The data displayed on the stat.ink public site is now correct.

This comment is a record just in case.

**Comment by frozenpandaman** [comment]
Yay, thanks so much @fetus-hina! Appreciate your help here.
