### ISSUE TITLE
UTF-8 AttributeError

### ISSUE THREAD

**Issue by AXU9513** [frozenpandaman/s3s#33]
https://github.com/frozenpandaman/s3s/blob/8dcff70b465e9343d93cf6d09ec2b86a754d3a6e/s3s.py#L19

I got an error from this line.

```
Traceback (most recent call last):
  File "s3s.py", line 19, in <module>
    sys.stdout.reconfigure(encoding='utf-8') # note: please stop using git bash
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'
```

Did a little search and found that upgrading Python to version 3.7 (and above) could be a work-a-round. ( I was running with Python 3.6.7, which I believe is the default version installed on macOS). 

Maybe there is no need to fix this, and it's ok to just remind the user to check the python version

**Comment by frozenpandaman** [comment]
Thanks for the heads up! Python 3.6 came out in 2016 and it reached end-of-life with no further security support at the end of 2021, so I think it's safe(st!) to suggest people get a newer version. However, googling shows that the default version that comes on (newer, at least) Macs is Python 3.8.9? That said, I tried to work around it by running the line only if Python 3.7+ is being used:

https://github.com/frozenpandaman/s3s/blob/7796903288e6f5b0441d32d507e277899bd7eccf/s3s.py#L19-L20
