### ISSUE TITLE
Exception ignored with I/O redirect on Linux

### ISSUE THREAD

**Issue by Ogekuri** [frozenpandaman/s3s#39]
I'm redirecting stdout and stderr in linux for daemon log purpose and I'm getting this error:
```
Exception ignored in: <function SquidProgress.__del__ at 0x7f136e9718c8>
Traceback (most recent call last):
  File "s3s.py", line 1022, in __del__
    sys.stdout.write(f"\r{' '*(os.get_terminal_size()[0] - 1)}\r")
OSError: [Errno 25] Inappropriate ioctl for device
```
Anyway it's seem run and terminate correctly.

**Comment by niyari** [comment]
Sorry. There was an omission in the change.
If there is a squid swimming in the log, it seems to work just by modifying this line, can you try to see if the error disappears?

https://github.com/frozenpandaman/s3s/blob/1e0bc147d7229d6d656cfce46d54c00026e7579d/s3s.py#L1022
`		sys.stdout.write(f"\r{' '*(shutil.get_terminal_size()[0] - 1)}\r")`
Change from `os.` to `shutil.`

**Comment by Ogekuri** [comment]
Thanks!
Sure, but currently I'm travelling, I'll be back on wednesday and I'll test it.

**Comment by fetus-hina** [comment]
Same here and created PR #42

This error also occurs every time it is run as a cron job.
(I run s2s, s3s with cron)

**Comment by niyari** [comment]
If the error continues to occur, one more step needs to be added.
Terminate SquidProgress explicitly.

**Comment by Ogekuri** [comment]
> Change from os. to shutil.

It's work for me. Thanks!

**Comment by frozenpandaman** [comment]
Sorry for the late reply, I was traveling.

Thanks for catching this!
