### ISSUE TITLE
Exported salmon run JSON doesn't seem to include results in the previous shift

### ISSUE THREAD

**Issue by k-ashiya** [frozenpandaman/s3s#4]
Hi, thank you for releasing s3s with export mode!

I've exported all JSONs, but salmon run JSON seems to include results only in the current shift, not in the previous one.
For instance, I've played 24 times in the 1st shift and 26 times in the 2nd, but JSON files only include the latest 26 results.

This is probably because of these lines in s3s.py:

> 					for j in query1_resp["data"]["coopResult"]["historyGroups"]["nodes"][0]["historyDetails"]["nodes"]:
> 						job_ids.append(j["id"])

`query1_resp["data"]["coopResult"]["historyGroups"]["nodes"]` is an array of the number of shifts, and these lines (unintentionally) choose the latest one.

**Comment by frozenpandaman** [comment]
Aha! Thanks, good catch. I'll get this fixed shortly (probably tomorrow, not today, sorry!)

**Comment by frozenpandaman** [comment]
Fixed now!

(I wonder if battles ever come in arrays, or if those are safe to always access via `[0]`…? Just in case I iterated through those too.)
