### ISSUE TITLE
Error with Exit code 1 while there's no battle/jobs with "-r"

### ISSUE THREAD

**Issue by ADeeeee** [frozenpandaman/s3s#48]
**Output:**
```
$ python3 s3s.py -r
Checking if there are previously-unuploaded battles/jobs...
No previously-unuploaded battles found.
Please specify whether you want to upload battle results (-nsr) or Salmon Run jobs (-osr). Exiting.
ERROR: 1
```
**Version:**
s3s v0.1.5
Latest commit e3abfda1324beb749e957970c8c1e348dacdf527

**Expect:**
no battle/jobs need to be uploaded
EXIT successfully with 0

Detail:
I understand that exit code 1 is for warning, but "-r" worked as expect without any errors and users should do nothing with it. Shouldn't it be 0? It looks like I am using a wrong argument and need to try -osr or -nsr instead.

**Comment by frozenpandaman** [comment]
This is kind of a weird edge case.

If running s3s without `-M`, the script will prompt you to upload up to 50 battles OR jobs at a time – you need to specify which using `-nsr` or `-osr`. This is a behavior which I think essentially no one really uses but it was the very first function of the original script, splatnet2statink.

When you ran it with `-r`, it checked for both unuploaded battles (and it found none) and Salmon Run jobs (actually not yet implemented), but then proceeded to ask "how many results should I upload, 0–50?" – but you did not specify what type of results, so it exited with that error.

I think I should probably suppress that `"Please specify whether…"` print line, though just for simplicity's sake, thanks.

**Comment by frozenpandaman** [comment]
@ADeeeee Let me know how the behavior seems to you now. Should be fixed.

**Comment by ADeeeee** [comment]
In general, I do feel the users need to do something, which means they're using it wrong, with the exit code 1, 2 or others. There're many situations looks like it's actually wrong. Maybe we should look at why "-r" is leading to "Please specify whether you want to upload battle results (-nsr) or Salmon Run jobs (-osr)" when it finished normally.

**Comment by frozenpandaman** [comment]
>Maybe we should look at why "-r" is leading to "Please specify whether you want to upload battle results (-nsr) or Salmon Run jobs (-osr)" when it finished normally.

I agree, which is why I fixed/changed that now. :)
