### ISSUE TITLE
s3s does not send some information for private battles

### ISSUE THREAD

**Issue by fetus-hina** [frozenpandaman/s3s#53]
If you play the mode for ranked battles (i.e., SZ, TC, RM or CB) in Private Battles, the information is not sent whether you are knocked out or not.
Judd results (% vs % in TW, count vs count in ranked modes) are not sent either.

Because s3s controls the send of these information whether the mode is [`REGULAR`, `FEST`](https://github.com/frozenpandaman/s3s/blob/79a64e5c46d55531d9a4f172291e386ec049d8e5/s3s.py#L522) or [`BANKARA`](https://github.com/frozenpandaman/s3s/blob/79a64e5c46d55531d9a4f172291e386ec049d8e5/s3s.py#L538).
When the `vsMode` is `PRIVATE`, the `vsRule` must be examined to determine which additional information to use.

![image](https://user-images.githubusercontent.com/848666/196894073-c4df2610-2951-4e81-b6e4-3a12d9f7e4f6.png)

**Comment by frozenpandaman** [comment]
Thanks!!
