### ISSUE TITLE
Crash while preparing result ('rank_before_s_plus')

### ISSUE THREAD

**Issue by tetrahedrl** [frozenpandaman/s3s#58]
Hi, 
After updating to the latest commit, attempting to use -r crashes with a KeyError for rank_before_s_plus. 
The error is below. Thanks!

> Checking if there are previously-unuploaded battles/jobs...
> Previously-unuploaded battles detected. Uploading now...
> Traceback (most recent call last):
>   File "/home/ry/s3s/s3s.py", line 1253, in <module>
>     main()
>   File "/home/ry/s3s/s3s.py", line 1229, in main
>     check_if_missing(which, True if secs != -1 else False, blackout, test_run)
>   File "/home/ry/s3s/s3s.py", line 899, in check_if_missing
>     fetch_and_upload_single_result(id, noun, ismonitoring, isblackout, istestrun)
>   File "/home/ry/s3s/s3s.py", line 848, in fetch_and_upload_single_result
>     post_result(result, ismonitoring, isblackout, istestrun)
>   File "/home/ry/s3s/s3s.py", line 696, in post_result
>     payload = prepare_battle_result(results[i]["data"], ismonitoring, overview_data)
>   File "/home/ry/s3s/s3s.py", line 606, in prepare_battle_result
>     if payload["rank_before_s_plus"]:
> KeyError: 'rank_before_s_plus'

**Comment by Toufool** [comment]
I think its probably crashing because you are not in S+ (obviously needs to be fixed). But first can you confirm what your current rank is?

**Comment by tetrahedrl** [comment]
Yeah, makes sense. I’m in S, not S+.
