### ISSUE TITLE
allow battles to be sent with invalid (hackers') weapon IDs

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#61]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/7245874/197714923-5f5b5b37-76dd-4695-8fa2-20eb3d0d5bb1.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/7245874/197714971-8abd09f0-60ce-4592-a6a5-b1b560d57f51.png">

Either we should match against a specific set of invalid/hacked (Grizzco) weapon IDs and blank these out if they occur in a battle JSON, so that the result can still be uploaded to stat.ink without the error above, or stat.ink should change to allow invalid and/or Grizzco weapon IDs being sent.

**Comment by OctoFloofy** [comment]
Here the requested match files 
[export-1666707371.zip](https://github.com/frozenpandaman/s3s/files/9861116/export-1666707371.zip)

**Comment by frozenpandaman** [comment]
@OctoFloofy Thanks!
