### ISSUE TITLE
Skip battles uploaded by s3si.ts

### ISSUE THREAD

**Issue by spacemeowx2** [frozenpandaman/s3s#65]
Because s3s and s3si.ts use different namespace to calculate uuid, so for the same battle the two software will generate different uuid.

Currently s3si.ts calculates the uuid of two namespaces to prevent duplication. Maybe adding this detection to s3s would be more user-friendly for users who are willing to experiment?

https://github.com/spacemeowx2/s3si.ts/blob/24384c2a11bb1e54790069197c3770afc7bb7808/src/exporters/stat.ink.ts#L101-L108

**Comment by fetus-hina** [comment]
I see no positive reason to use a dedicated namespace for s3sti.
Wouldn't it be enough to use the same namespace as s3s?

**Comment by spacemeowx2** [comment]
The API description for stat.ink does not express the intent of this namespace, so I used my own UUID. 

I also don't think it's a good idea to use the new namespace now. I think s3si.ts will change the namespace to s3s one

**Comment by frozenpandaman** [comment]
Agreed with Hina. I don't want to make s3s unnecessarily complex by manually adding in functionality to support the specific namespaces of other projects. I also don't know why people would use both of these projects together and not just one or the other, so users should not actually run into issues with duplicates being uploaded.

**Comment by fetus-hina** [comment]
The API documentation was written when no client other than s3s existed and was unlikely to appear in the FUTURE.
I thank you for respecting that statement.

To avoid this confusion, I will update the API documentation regarding the generation of the s3s method.

**Comment by niyari** [comment]
Why not take this opportunity to review the UUID generation rules once again?
It will take some time since it is already in operation, but it should be beneficial to users.

In Splatoon3, there is now one saved data per account.
Therefore, hash values can be correctly generated from the data that can be retrieved from the current Splatnet3.

**Comment by hasegaw** [comment]
stat.ink defined s3s's uuid generation method as standard regarding previous discussions.
https://github.com/frozenpandaman/s3s/issues/29#issuecomment-1259398917

**Comment by niyari** [comment]
![vsh](https://user-images.githubusercontent.com/2970321/198277885-538b0ea0-6030-4abe-91ec-46316b081fb3.png)
It is thought that the same account is no longer playing at the same time.
I assumed that it would be unique by combining a UserID and time.


![coh](https://user-images.githubusercontent.com/2970321/198279609-5b024b03-9c93-4fe0-8894-ff66663fa38d.png)
Same for salmon run.
But the proposal came too late.

**Comment by spacemeowx2** [comment]
@niyari My guess is that UUID(or session id?) is to prevent time drift between servers. Nevertheless, I assume that uid+timestamp is enough to distinguish a battle. So I chose userid+timestamp as the filename when exporting to files.
