### ISSUE TITLE
Stat.ink new adaptation

### ISSUE THREAD

**Issue by Sichongzou** [frozenpandaman/s3s#69]
Hello, author, I don't know if you noticed that Stat.ink had a data update three days ago, which supports uploading clothing information in the battle to Stat Ink I don't know whether you will adapt to this update. You can browse the details https://blog.fetus.jp/202211/961.html

**Comment by frozenpandaman** [comment]
Yes! @fetus-hina alerted me to this. I'll try to get some basic support added by the Splatfest. :)

**Comment by frozenpandaman** [comment]
@Sichongzou This is now supported!

<img width="258" alt="image" src="https://user-images.githubusercontent.com/7245874/201794307-baa7a516-00ad-4983-ba4b-275a46ff56d0.png">

**Comment by Sichongzou** [comment]
Ok, thank you for your time and efforts for this project
