### ISSUE TITLE
acc_lang and acc_country not set for manual token input 

### ISSUE THREAD

**Issue by AXU9513** [frozenpandaman/s3s#7]
Hello,

Thank you for putting so much effort and time in this project these days.

I'm getting the following error when I choose to skip the token generation and type the `gtoken` and `bulletToken` by myself.
```
Traceback (most recent call last):
  File "s3s.py", line 865, in <module>
    main()
  File "s3s.py", line 789, in main
    prefetch_checks()
  File "s3s.py", line 166, in prefetch_checks
    gen_new_tokens("blank")
  File "s3s.py", line 210, in gen_new_tokens
    CONFIG_DATA["acc_loc"] = acc_lang + "|" + acc_country
UnboundLocalError: local variable 'acc_lang' referenced before assignment
```

Probably because `acc_lang` and `acc_country` are acquired in `iksm.get_gtoken()`, but skipped in `iksm.enter_tokens()`

**Comment by frozenpandaman** [comment]
Whoops! Good catch, thanks. Fixed! (I just made it use `en-US` and `US` by default, but I guess we could prompt people to enter values too, though four different input prompts is kind of a lot, and it really won't change anything anyway when it comes to uploading the battles to stat.ink in the future…)
