### ISSUE TITLE
[Bug] About the dress skills when synchronizing to stat.ink

### ISSUE THREAD

**Issue by Sichongzou** [frozenpandaman/s3s#70]
Hello, author. I used the s3s program just released today. However, I found a problem when using the stat The third small skill in the link is always a question mark, no matter whether the third skill exists in the clothes I wear. I'm sure this is a bug. You can check the game https://stat.ink/ @Sichongzou/spl3/972746be-f968-44b4-8ab5-4bba36612bd7

In this game, the third skill of clothes and shoes I wear is the same as the first two skills, but it always shows that this is a question mark

**Comment by frozenpandaman** [comment]
Hmm, that's weird! I don't know & can't tell why this is happening. Will look into it and aim to get it fixed quickly, thanks for the heads up.

**Comment by frozenpandaman** [comment]
Just so I'm not misunderstanding, @Sichongzou…

>The third small skill in the link is always a question mark, no matter whether the third skill exists in the clothes I wear. 

>the third skill of clothes and shoes I wear is the same as the first two skills, but it always shows that this is a question mark

To me, these are saying two different things:
- 1\) The gear ability slot does not exist, e.g. is only 1-star or 2-star gear (you need to spend a Super Sea Snail to add it)
- 2\) The gear ability is locked ("?") but will unlock with enough EXP

To clarify, which of those two problems are you running into?

**Comment by Sichongzou** [comment]
Oh, I'm sorry. Maybe I said there was a problem. I mean, my clothes and shoes have the third skill, but there is no one on stat.ink
![Screenshot_2022-11-15-16-39-40-359_com nintendo z](https://user-images.githubusercontent.com/68594934/201871317-f710a4af-611c-4855-96c8-1cb444b2692b.jpg)

**Comment by frozenpandaman** [comment]
Ohhh, I see. I made a really dumb, small error with the code… 🥲

Fixed now!!

**Comment by Sichongzou** [comment]
Thank you. If I encounter other problems, I will submit new issues. Thank you for your time and effort on this project ❤️
