### ISSUE TITLE
f-API ‘hashMethod’ parameter

### ISSUE THREAD

**Issue by CafeAuLait-CC** [frozenpandaman/s3s#73]
Hello,

According to the author’s comment in this issue: https://github.com/imink-app/f-API/issues/1#issuecomment-1320738767
I think maybe you would like to update this parameter to `hash_method` instead of `hashMethod`.

https://github.com/frozenpandaman/s3s/blob/06adee6add15dbadff2dfd6fda5281b8e49cf0a3/iksm.py#L422

It won’t affect the functionality though.

**Comment by frozenpandaman** [comment]
Thanks! (IIRC, only the latter camelCase one originally worked, even though the documentation said otherwise, so that's what we've been using up until now. I just double-checked with Jone as well to make sure and the snake_case one is indeed preferred & more accurate!)
 
Updated in df1938b.
