### ISSUE TITLE
Salmon Run

### ISSUE THREAD

**Issue by Sichongzou** [frozenpandaman/s3s#76]
Hello, author. I found Stat.ink currently supports Salmon Run. Although there is no interface to display it, data can be uploaded through the API. For details, you can view Stat.ink's issues
https://github.com/fetus-hina/stat.ink/issues/1128

**Comment by frozenpandaman** [comment]
SR support is all ready to go (I've tested everything and have my recent jobs uploaded, no errors 😁) but I think waiting for Hina to finish making the graphical UI for it, so you can actually see what's uploaded on your account on the site, will be best. IMO there's no real point of having it uploaded at this point if it's impossible to see, and confirming which jobs are there require making a manual call to another API endpoint… which most users are not going to want to do, and again, I don't really see why this is needed at this point either.

I did ask Hina a couple days ago for an estimate as to when it will be supported on the site itself, not just through the API, and he told me "maybe less than a week" so here's hoping!

**Comment by Sichongzou** [comment]
OK, thank you very much for adapting this update, and thank you very much for your time and effort in this project
![UU~2)MCOM$I4OJ1SWX2J3XR](https://user-images.githubusercontent.com/68594934/202975125-9ba71a31-0058-4fe8-a7cb-35d7d3b1bd39.jpg)

**Comment by fetus-hina** [comment]
Sorry to keep you waiting.
Let me show you a little bit about the current status 😁

![image](https://user-images.githubusercontent.com/848666/203169670-695a7590-41d9-43a9-8662-0aff6846d81d.png)

**Comment by frozenpandaman** [comment]
Wow @fetus-hina, looks great!!! Can't wait! (oh noo, that was from last rotation when I ranked down two levels 😭)

**Comment by Sichongzou** [comment]
@fetus-hina Wow，This looks great
