### ISSUE TITLE
Eliminate mmh3 library dependencies

### ISSUE THREAD

**Issue by niyari** [frozenpandaman/s3s#77]
To use mmh3 on Windows, the C++ code must be built. 
As an additional step, a build tool must also be installed.
Generally, Windows does not come with build tools preinstalled.
For this reason, attempts to install the mmh3 library from pip will fail.
This library is used less frequently than play data and is used to export data to other tools. replacing mmh3 with an alternative code would have little impact.

(So I wrote the code to add it to utils.py, but I have no data to verify!)

**Comment by frozenpandaman** [comment]
Thank you for the report! I saw [your tweet](https://twitter.com/sou_niyari/status/1594389758037217282) as well, just haven't had time to reply as I will be traveling through this weekend. Do you know why this module requires that on Windows? On Mac it can be installed easily with pip with no problems.

Unless there's a way around this, I can take it out of `requirements.txt` and make it so users have to manually install this module.

**Comment by frozenpandaman** [comment]
Perhaps pymmh3 could be used instead?

https://github.com/wc-duck/pymmh3

**Comment by niyari** [comment]
> Maybe pymmh3 could be used instead? https://github.com/wc-duck/pymmh3

Probably not a problem.
The environment that can be tested immediately has the build tool already installed, so we have not verified it exactly.

And here is the pre-test code. [https://gist.github.com/niyari/52169f00abe6445b1f6ea5950c81b16d](https://gist.github.com/niyari/52169f00abe6445b1f6ea5950c81b16d)

**Comment by frozenpandaman** [comment]
Makes sense, thank you! Rather than use our own implementation, I think the pure Python implementation pymmh3 should work well. I'll change the project from using mmh3 to pymmh3, which should avoid requiring C++ build tools (!) to be installed for some users.

**Comment by frozenpandaman** [comment]
Fixed/mitigated in c6e9694. ありがとう！

**Comment by niyari** [comment]
Additional testing confirmed no C++ build tools dependencies.
