### ISSUE TITLE
Incorrect uuid generation

### ISSUE THREAD

**Issue by spacemeowx2** [frozenpandaman/s3s#79]
According to the documentation, the uuid of SALMON RUN should use the whole base64 decode result.

> When posting to stat.ink from data obtained from SplatNet, we expect the following method to generate a uuid.
> This method IS DIFFERENT with the Battle API.
> 
>    decode Base64'ed ID from coopHistoryDetail.id ("CoopHistoryDetail-u-..." )
>    Calc UUIDv5 with namespace f1911910-605e-11ed-a622-7085c2057a9d
> ```
> $theUUID = uuid_v5(
>   base64_decode($history->id),
>   uuid_from_string('f1911910-605e-11ed-a622-7085c2057a9d'),
> );
> ```
> From: https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Salmon-%EF%BC%8D-Post#splatnet-data-based-uuid

But the entire id is not used in s3s:

https://github.com/frozenpandaman/s3s/blob/1bcdedac88fd987025e045973cd2850da90904e4/s3s.py#L758-L759

**Comment by frozenpandaman** [comment]
Thank you! Oops…

Fixed in s3s v0.2.1 (5e25859).
