### ISSUE TITLE
Cannot parse SR weapons exported in non-English when using `-i`

### ISSUE THREAD

**Issue by paul-sama** [frozenpandaman/s3s#80]
`python3 s3s.py -i export-1668657854/coop_results.json export-1668657854/overview.json`

upload history jobs, but the files export not in English,
it's result
```
Error uploading job. Message from server:
{
    "error": {
        "players": "weapons: Weapons is invalid."
    }
}
```

**Comment by paul-sama** [comment]
https://stat.ink/api/v3/weapon?full=1

```

{
  "23900, grizzco_slosher": "kuma_slosher",
  "熊先生印章泼桶": "kuma_slosher",
  "Bär-Schwapper": "kuma_slosher",
  "Grizzco Slosher": "kuma_slosher",
  "Derramatic Don Oso": "kuma_slosher",
  "Seau M. Ours SA": "kuma_slosher",
  "Seau M. Ours Cie": "kuma_slosher",
  "Secchiostro Ursus": "kuma_slosher",
  "Beer & Co-morser": "kuma_slosher",
  "Ведроган «Потапыч Inc.»": "kuma_slosher",
  "クマサン印のスロッシャー": "kuma_slosher",
  "熊先生商會潑桶": "kuma_slosher",
  "20900, grizzco_blaster": "kuma_blaster",
  "熊先生印章爆破枪": "kuma_blaster",
  "Bär-Blaster": "kuma_blaster",
  "Grizzco Blaster": "kuma_blaster",
  "Devastador Don Oso": "kuma_blaster",
  "Lanzamotas Don Oso": "kuma_blaster",
  "Blaster M. Ours SA": "kuma_blaster",
  "Blasteur M. Ours Cie": "kuma_blaster",
  "Blaster Ursus": "kuma_blaster",
  "Beer & Co-blaster": "kuma_blaster",
  "Бластер «Потапыч Inc.»": "kuma_blaster",
  "クマサン印のブラスター": "kuma_blaster",
  "熊先生商會爆破槍": "kuma_blaster",
  "Mr. 베어표 블래스터": "kuma_blaster",
  "27900, grizzco_stringer": "kuma_stringer",
  "熊先生印章猎鱼弓": "kuma_stringer",
  "Bär-Stringer": "kuma_stringer",
  "Grizzco Stringer": "kuma_stringer",
  "Arcromatizador Don Oso": "kuma_stringer",
  "Transperceur M. Ours SA": "kuma_stringer",
  "Transperceur M. Ours Cie": "kuma_stringer",
  "Calamarco Ursus": "kuma_stringer",
  "Beer & Co-spanner": "kuma_stringer",
  "Тетиватор «Потапыч Inc.»": "kuma_stringer",
  "クマサン印のストリンガー": "kuma_stringer",
  "熊先生商會獵魚弓": "kuma_stringer",
  "Mr. 베어표 스트링거": "kuma_stringer",
  "22900, grizzco_charger": "kuma_charger",
  "熊先生印章蓄力狙击枪": "kuma_charger",
  "Bär-Konzentrator": "kuma_charger",
  "Grizzco Charger": "kuma_charger",
  "Cargatintas Don Oso": "kuma_charger",
  "Fusil M. Ours SA": "kuma_charger",
  "Fusil M. Ours Cie": "kuma_charger",
  "Splatter Ursus": "kuma_charger",
  "Beer & Co-lader": "kuma_charger",
  "Сплатган «Потапыч Inc.»": "kuma_charger",
  "クマサン印のチャージャー": "kuma_charger",
  "熊先生商會蓄力狙擊槍": "kuma_charger",
  "26900, grizzco_brella": "kuma_shelter",
  "熊先生印章防空伞": "kuma_shelter",
  "Bär-Pluviator": "kuma_shelter",
  "Grizzco Brella": "kuma_shelter",
  "Paratintas Don Oso": "kuma_shelter",
  "Para-encre M. Ours SA": "kuma_shelter",
  "Para-encre M. Ours Cie": "kuma_shelter",
  "Sparasole Ursus": "kuma_shelter",
  "Beer & Co-plenzer": "kuma_shelter",
  "Зонтган «Потапыч Inc.»": "kuma_shelter",
  "クマサン印のシェルター": "kuma_shelter",
  "熊先生商會防空傘": "kuma_shelter",
  "Mr. 베어표 셸터": "kuma_shelter"
}
```

**Comment by qjzcj2008** [comment]
I met this problem too, and I looked up the s3s codes and stat.ink API docs. This's due to Splatnet3 just uses plain text to present weapons you used in Salmon Run part rather than uses ids. And s3s requests and parses SR information with English and converts weapons' Eng name string to weapon keys which stat.ink can prosess.

I think maybe it's hard to do compatiblity job on s3s side, it will increase the complication of s3s project, and there's less chance to use the import function as now we can upload infos directly to stat.ink. Maybe @frozenpandaman should mention this in readme to note people who exported infos with non-English to do some compatiblity job on their own side.

And in earlier issuses, you mentioned you are using CHS, so am I. And I had done the compatiblity job for CHS exported SR files. I wrote this just for myself, so it's kind of rough, but it workd fine for me. You can try this [here](https://github.com/qjzcj2008/s3s/tree/job_chs_support)`https://github.com/qjzcj2008/s3s/tree/job_chs_support`. And I disabled the auto-update function, cuz it's just a workaround.

And also I got something interesting here when I uploaded my job history, there's a job(only this one and I appended it in the end) which bosses I defeated plus teammates defeated is greater than the bosses poped up. Kind of weird. Curiously is there anyone else meet this problem too. And here is the SR data.
```json
{{
                        "defeatCount":2,
                        "teamDefeatCount":6,
                        "popCount":6,
                        "enemy":{
                            "id":"Q29vcEVuZW15LTY=", 
                            "name":"铁板鱼(Scrapper)",
                            "image":{
                                "url":"",
                            }
                        }
                    },
                    {
                        "defeatCount":1,
                        "teamDefeatCount":4,
                        "popCount":4,
                        "enemy":{
                            "id":"Q29vcEVuZW15LTEy", 
                            "name":"潜水鱼(Flipper-Flopper)",
                            "image":{
                                "url":"",
                            }}
```

**Comment by Mixaz017** [comment]
> there's a job(only this one and I appended it in the end) which bosses I defeated plus teammates defeated is greater than the bosses poped up.

I believe defeatCount is how many you defeated out of teamDefeatCount, so nothing weird. defeatCount never goes higher than teamDefeatCount.

**Comment by qjzcj2008** [comment]
> > there's a job(only this one and I appended it in the end) which bosses I defeated plus teammates defeated is greater than the bosses poped up.
> 
> I believe defeatCount is how many you contributed to teamDefeatCount, so nothing weird. defeatCount never goes higher than teamDefeatCount.

Oh! I think you're right, the data I posted earlier isn't from the job which failed to upload. I rechecked it, and I edited my earlier post.

**Comment by Mixaz017** [comment]
> Oh! I think you're right, the data I posted earlier isn't from the job which failed to upload. I rechecked it, and I edited my earlier post. In this error case I met, defeatCount really goes higher than teamDefeatCount. Something weird really happend. Not sure what's going wrong in this case.
> 
> Curiously is there anyone else meet this problem too. 👀
Interesting, maybe this could be caused by teammates disconnecting? I think this is getting off-topic and should be discussed in another issue.

**Comment by OctoFloofy** [comment]
> And also I got something interesting here when I uploaded my job history, there's a job(only this one and I appended it in the end) which bosses I defeated plus teammates defeated is greater than the bosses poped up. Kind of weird. Curiously is there anyone else meet this problem too. And here is the SR data.
> ```json
> {{
>                         "defeatCount":2,
>                         "teamDefeatCount":1,
>                         "popCount":3,
>                         "enemy":{
>                             "id":"Q29vcEVuZW15LTY=", 
>                             "name":"铁板鱼(Scrapper)",
>                             "image":{
>                                 "url":"",
>                             }
>                         }
>                     }
> }
> ```
> 
> And here is what I got:
> `Error uploading job. Message from server:`
> ```json
> {
>     "error": {
>         "bosses": "Bosses.teppan.defeated_by_me is invalid. Defeated By Me must be less than or equal to \"Defeated\"."
>     }
> }
> ```

I'm getting this error too

**Comment by fetus-hina** [comment]
The broken data like `defeatCount(defeated_by_me) > teamDefeatCount(defeated)` are now accepted by stat.ink.
However, such data is difficult to handle, so you may see "it looks this data is corrupt" in some section.

**Comment by frozenpandaman** [comment]
Thanks Hina! For the other issue (weapon detection for non-English languages) I'll be able to look into it later this week.

**Comment by qjzcj2008** [comment]
Thanks @fetus-hina ,do you need me to provide the broken splanet SR data to you?👀 I'm willing to open an issue on stat.ink's github page and provide this broken data to you.😊

**Comment by fetus-hina** [comment]
No need for this case.
If you encounter another issue that we (Eli and I) are not known, please create a new issue to s3s and/or stat.ink to let us know.

**Comment by frozenpandaman** [comment]
>I think maybe it's hard to do compatiblity job on s3s side, it will increase the complication of s3s project, and there's less chance to use the import function as now we can upload infos directly to stat.ink [...] people who exported infos with non-English to do some compatiblity job on their own side.
> 
>  You can try this [here](https://github.com/qjzcj2008/s3s/tree/job_chs_support) `https://github.com/qjzcj2008/s3s/tree/job_chs_support`

Thank you @qjzcj2008! I don't think this is possible for s3s to fix on our end. It's a pretty niche issue, and only a problem in the following case:
1) A user has exported files (`-o`) using a version of s3s below v0.2.0, and is now trying to upload them
2) The user is (was) using SplatNet in a language other than English

**For those encountering this issue, they should make a temporary, local change similar to what you have done here: https://github.com/frozenpandaman/s3s/commit/11981c80009a1e5d69bc66a7723ee2017685494f**

As the commit shows, the  `job_weapon` dictionary at the top needs to have keys & values in the following format:
`"Your language weapon name": "English weapon name",`

These can be sourced from https://stat.ink/api/v3/weapon?full=1.
https://splatoonwiki.org/wiki/List_of_weapons_in_Splatoon_3n may be useful too.
Remember, you only need to include weapons that were in the game as of Splatoon 3 [Ver.1.0.0](https://splatoonwiki.org/wiki/List_of_updates_in_Splatoon_3) (prior to Chill Season 2022).

We will ask @fetus-hina about keeping track of weapon image hashes on the stat.ink side – only the 55 weapons present at launch would need to be included, and if this database is not updated it will still work fine.

**Comment by frozenpandaman** [comment]
>I think maybe it's hard to do compatiblity job on s3s side, it will increase the complication of s3s project, and there's less chance to use the import function as now we can upload infos directly to stat.ink [...] people who exported infos with non-English to do some compatiblity job on their own side.
> 
>  You can try this [here](https://github.com/qjzcj2008/s3s/tree/job_chs_support) `https://github.com/qjzcj2008/s3s/tree/job_chs_support`

Thank you @qjzcj2008! I don't think this is possible for s3s to fix on our end. It's a pretty niche issue, and only a problem in the following case:
1) A user has exported files (`-o`) using a version of s3s below v0.2.0, and is now trying to upload them (`-i`)
2) The user is/was using SplatNet in a language other than English

**For those encountering this issue, they should make a temporary, local change similar to what you have done here: https://github.com/frozenpandaman/s3s/commit/11981c80009a1e5d69bc66a7723ee2017685494f**

As the commit shows, the  `job_weapon` dictionary at the top needs to have keys & values in the following format:
`"Your language weapon name": "English weapon name",`

These can be sourced from https://stat.ink/api/v3/weapon?full=1.
https://splatoonwiki.org/wiki/List_of_weapons_in_Splatoon_3n may be useful too.
Remember, you only need to include weapons that were in the game as of Splatoon 3 [Ver.1.0.0](https://splatoonwiki.org/wiki/List_of_updates_in_Splatoon_3) (prior to Chill Season 2022).

We will ask @fetus-hina about keeping track of weapon image hashes on the stat.ink side – only the 55 weapons present at launch would need to be included, and if this database is not updated it will still work fine.

**Comment by Mysterium-Mystery** [comment]
For anyone else that still has this problem, I wrote a quick fix for it. Should theoretically work for any language. You can find it here: https://github.com/Mysterium-Mystery/s3s-sr-language-fix

It should work, as I used it myself, but if you encounter any problems, feel free to contact me

**Comment by Mysterium-Mystery** [comment]
No problem ^^ Ok, that's good to know

Very good suggestion. I honestly didn't even think about that because I always had the file in some other random place xD
I don't know if there's anything that still needs to be discussed but if there is, we can definitely do that :)

But I actually do have one more question. It's not really related to this topic, so sorry if this isn't the right place to ask.
In the exported files, I noticed there's one file (results.json) that still produced an error and it's just filled with this " {"errors": [{"message": "PersistedQueryNotFound"}]} ". I know that I played ranked shortly before that and this was also still before the update (26.11). As everything gets uploaded now anyways, this doesn't really matter but I'm just curious if you've got any idea what could've caused this

**Comment by frozenpandaman** [comment]
@Mysterium-Mystery Sounds like a different issue and I'm not sure immediately what could be causing it. Please send me a DM on Twitter (or email, listed on my website that's linked on my profile, if you prefer).

**Comment by frozenpandaman** [comment]
Hi @Mysterium-Mystery, a user reached out to me and mentioned that your repo didn't work for them – I took a look at the error they were getting and noticed you introduced some Python 3.10-specific code:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/7245874/206911252-e6d08e22-2b05-4223-af64-e30127eff095.png">

s3s supports Python 3.9, and asking a non-tech savvy user to upgrade just to use your fork here isn't ideal. Might it be possible for you to amend your code & implement the case statement using an if/else instead, so that your fork will still work for users running lower versions of Python 3? Thanks!!!

**Comment by Mysterium-Mystery** [comment]
Hi,
Sorry for the late reply. Again something I didn't even consider xD
Well, I changed it as you suggested and it should work now ^^
Oh and from now you can also open an issue on my repo. I just didn't know that I had to enable this feature (It's my first time using Github as repo-owner)
