### ISSUE TITLE
Salmon Run: Wrong Fail Reason

### ISSUE THREAD

**Issue by fetus-hina** [frozenpandaman/s3s#82]
When all the players wiped-out before reach to quota, [s3s sends `time_limit`](https://github.com/frozenpandaman/s3s/blob/1bcdedac88fd987025e045973cd2850da90904e4/s3s.py#L775-L777). In the case, client should send `wipe_out` instead of `time_limit`.

In practice, it may be better to always omit `fail_reason`, because it is difficult to determine the "fail reason" from SplatNet 3 data.

| Achieved Quota? | Real Reason | Expected | s3s |
|-|-|-|-|
| N | Time | Time | Time |
| N | Wipe | Wipe | **Time** |
| Y | Wipe | Wipe | Wipe |

Original Report: https://twitter.com/ch3cooh/status/1596721683670319106 (Japanese)

**Comment by frozenpandaman** [comment]
You're right, it is impossible – it seems – to always determine the reason a job was a failure. Sad… :(

Thanks for reporting this! I agree it is best to omit `fail_reason` unless it is 100% known.
