### ISSUE TITLE
Crash because Key Error

### ISSUE THREAD

**Issue by chanchancl** [frozenpandaman/s3s#87]
Here are logs, and I also pprint the result[i]

[logs.txt](https://github.com/frozenpandaman/s3s/files/10115155/logs.txt)

**Comment by frozenpandaman** [comment]
Thanks! Got this report from someone else as well:
![image](https://user-images.githubusercontent.com/7245874/204617640-aa953f14-d23b-4c92-98ed-5e5cf1ead397.png)

Will look into it and try to fix it ASAP.

**Comment by frozenpandaman** [comment]
Duplicate of #85
