### ISSUE TITLE
`title_exp_before` must be no greater than 999

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#90]
Bug report from [Minaraii](https://twitter.com/Minaraii) on Twitter:

![image](https://user-images.githubusercontent.com/7245874/204904195-a1b6016d-d7db-489c-9d97-4b1054ce4e13.png)
This error came from a W2 loss EVP 999 -> 994, which only happens when a match has 1 or more player DC.
I believe this is due to the data registering an EVP 999 final result as a 979 -> 999, regardless of the starting EVP (e.g. 980 / 985 / 990)?

[export.zip](https://github.com/frozenpandaman/s3s/files/10132520/export.zip)

**Comment by k-ashiya** [comment]
I guess the result says afterGradePoint is 995 and s3s assumes that 1005 -> 995 as a W2 loss, isn't it?

**Comment by frozenpandaman** [comment]
>tracing the previous result via previousHistoryDetail or passing EVP as next function args seems better

@k-ashiya I think you're right. It's slower (an extra request for every job) but it definitely is the most accurate.

This should be fixed in 10dd403!
