### ISSUE TITLE
Detecting & trying to upload unuploaded battles twice

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#91]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/7245874/205288112-399d4551-925a-4881-82fc-16fb7a75df4d.png">

**Comment by ADeeeee** [comment]
Python: 3.9.14
Branch: master
Commit: 22b22d7288

Mine goes a bit different that it detected the previous battles which were uploaded already first and then my two battles today event after the last battle about an hour (I only played two turf wars which is the last two below)

I also noticed that sometimes it uploaded nothing when the cronjob triggered the script and will keep looking at it by setting up the notification when it failed, which I forgot to do that, pardon me. Not sure it was failed or didn't detect the new battles and let's see in couple days.

```
$ ./s3s.py -r
s3s v0.2.4
Validating your tokens...

The stored tokens have expired.
Attempting to generate new gtoken and bulletToken...
Wrote tokens for xxxx to config.txt.

Checking if there are previously-unuploaded battles/jobs...
Previously-unuploaded battles detected. Uploading now...
Battle already uploaded - https://stat.ink/@ADe/spl3/7b11d104-07b8-4d65-8d4c-b35e93d732d2
Battle already uploaded - https://stat.ink/@ADe/spl3/dd903792-6d91-4440-a4c2-4c61a603f914
Battle already uploaded - https://stat.ink/@ADe/spl3/bd5a689b-f0df-47eb-bb69-a04ce6334718
Battle already uploaded - https://stat.ink/@ADe/spl3/21ca8096-2760-45fb-8beb-957655609bdb
Battle uploaded to https://stat.ink/@ADe/spl3/8b0b2f5e-16cd-4b2a-98d2-fd546b53b91a
Battle uploaded to https://stat.ink/@ADe/spl3/a818f996-efa0-427f-89c9-678a84c5a967
No previously-unuploaded jobs found.
```

**Comment by frozenpandaman** [comment]
It seems `fetch_json()` is returning some battles/jobs twice. I haven't had a chance to really look into this much (and it doesn't critically affect functionality or break the script, but I do want to fix it) but @CafeAuLait-CC do you think this could be something multithreading is causing?

**Comment by CafeAuLait-CC** [comment]
I don’t think it’s caused by multithreading at first glance. The `fetch_json()` method has a parameter `numbers_only`. Multithreading will only be used when `numbers_only` is set to `False`. But in `-r` mode, this parameter is explicitly set to `True`. 

https://github.com/frozenpandaman/s3s/blob/a10fe842c4368e162a2ba1cc2fba44559062c1e5/s3s.py#L1340

Actually, `fetch_json()` is called many times in the program, and the `-o` mode is the only place that `numbers_only` is set to `False`.

But I’ll double check that when I have time later.

**Comment by frozenpandaman** [comment]
Ahh, you're right, thanks. Yeah, most of the time we want the full data, but in `-r` when you're just comparing IDs to see what's not yet online (in `check_if_missing()`), you only care about that (and not the full `vsHistoryDetail`/`coopHistoryDetail` for each one which takes way longer to get).

I'm sure the problem is in `fetch_json()`, just not yet sure what changed or why it's occurring now…

**Comment by frozenpandaman** [comment]
Ahhh, it was a faulty if/else that was triggering when you had an `"ignore_private": "true"` line added to your `config.txt`… which I just recently added. 😅
