### ISSUE TITLE
Could not find and upload X match data to stat.ink

### ISSUE THREAD

**Issue by k3bluesky** [frozenpandaman/s3s#93]
s3s v0.2.2

**Comment by frozenpandaman** [comment]
See #92. It will be supported soon.

Currently live in the `x` branch: https://github.com/frozenpandaman/s3s/tree/x

**Comment by k3bluesky** [comment]
ok I see,  Thank you!

**Comment by frozenpandaman** [comment]
@k3bluesky X Battles are supported now. :)

**Comment by k3bluesky** [comment]
ok I got it, Thanks!
