### ISSUE TITLE
Occasionally exceptions raise running from crontab

### ISSUE THREAD

**Issue by Ogekuri** [frozenpandaman/s3s#97]
I'm still experience occasionally exception when I run s3s from crontab:

```
Traceback (most recent call last):
  File "s3s.py", line 1889, in <module>
    main()
  File "s3s.py", line 1883, in main
    fetch_and_upload_single_result(hash, noun, blackout, test_run) # not monitoring mode
  File "s3s.py", line 1302, in fetch_and_upload_single_result
    post_result(result, False, isblackout, istestrun) # not monitoring mode
  File "s3s.py", line 1114, in post_result
    payload = prepare_job_result(results[i]["data"], ismonitoring, isblackout, overview_data, prevresult=prevresult)
  File "s3s.py", line 878, in prepare_job_result
    prev_job = json.loads(prev_job_post.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It's start from **fetch_and_upload_single_result** after the **result_post = requests.post(utils.GRAPHQL_URL** that fail with **result_post.status_code == 401**.

This cause a fail on **json.loads(result_post.text)**  on the **fetch_and_upload_single_result**, but also the **json.loads(prev_job_post.text)** inside the **prepare_job_result**, that raise exceptions.

I don't where is better to fix it, if on **fetch_and_upload_single_result** or on **prepare_job_result**.

Could you try to check it?

Many thanks!

**Comment by frozenpandaman** [comment]
Thanks! I'm not sure why that request would fail, but if it does, I made it so it'll just pass silently (i.e. no data on previous job rank/points will be sent). Let me know if the changes in 368e519 fix this for you.

**Comment by Ogekuri** [comment]
Better, but I think that we have to wrap with a try/catch also the **json.loads(result_post.text)** on **fetch_and_upload_single_result** on line **1303**.

Here the error that still occur:
`
Traceback (most recent call last):
  File "s3s.py", line 1888, in <module>
    main()
  File "s3s.py", line 1882, in main
    fetch_and_upload_single_result(hash, noun, blackout, test_run) # not monitoring mode
  File "s3s.py", line 1303, in fetch_and_upload_single_result
    result = json.loads(result_post.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Many thanks!

**Comment by cesaregarza** [comment]
I suspect it’s caused by the GTOKEN expiring by the time the request is made, which would explain the 401 response. Regenerating on a not 200 might work, but I’ll need to do some testing to see if this is the cause.

**Comment by frozenpandaman** [comment]
See #101.
